type Employee={id:string;firstName:string;lastName:string;middleName:string;active:boolean};
type Contribution={name:string;value:number};
type HiredWorker={fullName:string;position:string};
type HiredDetail=HiredWorker&{responsible:string};
type PlannedDismissal={first_name:string;last_name:string;middle_name:string};
type PeopleCategory='invited_candidates'|'interviewed_candidates'|'interns'|'reserve_candidates'|'dismissed_workers';
type PeopleKey='invitedCandidates'|'interviewedCandidates'|'interns'|'reserveCandidates'|'dismissedWorkers';
type Row={id:string;officeId:string;officeName:string;sortOrder:number;openVacancies:number;invitedCandidates:number;interviewedCandidates:number;interns:number;plannedReserve:number;reserveCandidates:number;dismissedWorkers:number;staffPositionsCount:number;activeEmployeesCount:number;vacantPositionsCount:number;traineesCount:number;traineesCountChange?:number;recruitmentCount:number;plannedDismissalsCount:number;plannedDismissals:PlannedDismissal[];efficiency:number;efficiencyPlan:number;invitationPlan:number;hiringPlan:number;invitationEfficiency:number;hiringEfficiency:number;hiredWorkers:HiredWorker[];hiredDetails?:HiredDetail[];people:Partial<Record<PeopleCategory,string[]>>;peopleDetails?:Partial<Record<PeopleCategory,HiredDetail[]>>;contributions?:Record<string,Contribution[]>;responsibleCount:number;assigned?:boolean};
type Bootstrap={report:{id:string;date:string;status:string;editable:boolean;accessCount?:number};rows:Row[];plan:number;invitationPlan:number;hiringPlan:number;totals:Record<string,number>};
type User={id:string;employeeId?:string;username:string;role:'superadmin'|'admin'|'employee';firstName:string;lastName:string;middleName:string;active?:boolean;plan:number;planFrom:string;nextPlan:number;nextPlanFrom:string;mainOfficePlan:number;mainOfficePlanFrom:string;nextMainOfficePlan:number;nextMainOfficePlanFrom:string;invitationPlan:number;invitationPlanFrom:string;nextInvitationPlan:number;nextInvitationPlanFrom:string;mainOfficeInvitationPlan:number;mainOfficeInvitationPlanFrom:string;nextMainOfficeInvitationPlan:number;nextMainOfficeInvitationPlanFrom:string};
type DailyPlan={userId:string;name:string;plan:number;invitedPlan:number;hiredPlan:number;overridden:boolean};
type ReportAccessUser={id:string;firstName:string;lastName:string;middleName:string;accessUntil?:string};
type ResponsibleUser={id:string;firstName:string;lastName:string;middleName:string;assigned:boolean};
type TraineeReport={report_type_id:number;department:string;report_date:string;reporter_id:number;trainee_id:number|null;full_name:string;status_id:string;source:string;interview_date:string|null;security_approval_date:string|null;internship_start_date:string|null;task_start_date:string|null;note:string;file_name:string;file_object_key:string;matches:{full_name:string;score:number}[]};
const content=document.querySelector<HTMLElement>('#content')!;
const modalRoot=document.querySelector<HTMLElement>('#modal-root')!;
const datePickerRoot=document.querySelector<HTMLElement>('#date-picker-root')!;
const appTooltip=document.querySelector<HTMLElement>('#app-tooltip')!;
const title=document.querySelector<HTMLElement>('#page-title')!;
const subtitle=document.querySelector<HTMLElement>('#page-subtitle')!;
const nav=document.querySelector<HTMLElement>('#nav')!;
const icon=(body:string)=>`<svg viewBox="0 0 24 24" aria-hidden="true">${body}</svg>`;
const icons={
  report:icon('<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 21V9"/>'),
  history:icon('<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2M3 12H1"/>'),
  employees:icon('<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>'),
  offices:icon('<path d="M3 21h18M5 21V7l7-4 7 4v14M9 10h.01M15 10h.01M9 14h.01M15 14h.01M10 21v-3h4v3"/>'),
  mainOffice:icon('<path d="M3 21h18M6 21V4h12v17M9 8h2M13 8h2M9 12h2M13 12h2M10 21v-5h4v5"/>'),
  imports:icon('<path d="M12 3v12M7 10l5 5 5-5M5 21h14"/>'),
  audit:icon('<path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/>'),
  left:icon('<path d="m15 18-6-6 6-6"/>'),right:icon('<path d="m9 18 6-6-6-6"/>'),
  columns:icon('<path d="M4 4h16v16H4zM9 4v16M15 4v16"/>'),reset:icon('<path d="M3 12a9 9 0 1 0 3-6.7L3 8M3 3v5h5"/>'),
  fullscreen:icon('<path d="M8 3H3v5M16 3h5v5M8 21H3v-5M16 21h5v-5"/>'),download:icon('<path d="M12 3v12M7 10l5 5 5-5M5 21h14"/>'),check:icon('<path d="m5 12 4 4L19 6"/>'),
  search:icon('<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>'),
  access:icon('<circle cx="8" cy="15" r="4"/><path d="m11 12 8-8M15 8l3 3M17 6l2 2"/>'),
  calendar:icon('<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>')
};
const reportPage=[['report',icons.report,'Ежедневный отчёт'],['main-report',icons.report,'Ежедневный отчет (ГО)'],['trainee-reports',icons.employees,'Отчеты по стажерам']];
let pages:string[][]=reportPage;
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
const dateObject=(value:string)=>new Date(value+'T12:00:00');
const dateValue=(value:Date)=>value.toISOString().slice(0,10);
const isWeekend=(value:string)=>{const day=dateObject(value).getDay();return day===0||day===6};
function nearestBusinessDate(value:string,direction:-1|1=-1){const date=dateObject(value);while(date.getDay()===0||date.getDay()===6)date.setDate(date.getDate()+direction);return dateValue(date)}
const businessToday=()=>nearestBusinessDate(today(),-1);
const displayDate=(value:string)=>dateObject(value).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'});
let currentPage='report', reportDate=today(), report:Bootstrap|null=null, saveTimers=new Map<string,number>();
let modalKeyHandler:((event:KeyboardEvent)=>void)|null=null;
let datePickerOutsideHandler:((event:PointerEvent)=>void)|null=null,datePickerKeyHandler:((event:KeyboardEvent)=>void)|null=null;
let currentUser:User|null=null,adminUsers:User[]=[];
let selectedEmployee='';
let reportSocket:WebSocket|null=null,reportRefreshTimer=0;
const debtsterRefreshInterval=5*60*1000,debtsterRefreshRetry=30*1000;
let debtsterRefreshTimer=0;
const dirtyRows=new Set<string>();
const defaultColumnWidths:Record<string,number>={office:200,staffPositionsCount:125,vacantPositionsCount:145,traineesCount:145,plannedDismissalsCount:145,openVacancies:130,invitedCandidates:135,interviewedCandidates:145,interns:145,plannedReserve:125,reserveCandidates:135,hires:135,invitationEfficiency:165,hiringEfficiency:165,responsibles:145};
const allColumns=[
  ['office','РП'],['openVacancies','Количество открытых вакансий'],
  ['invitedCandidates','Количество приглашенных кандидатов'],
  ['invitationEfficiency','% исполнения плана по приглашенным кандидатам'],
  ['interviewedCandidates','Количество прошедших собеседование'],['interns','Количество кандидатов на стажировке'],
  ['plannedReserve','Планируемый резерв'],['reserveCandidates','Количество кандидатов в резерве'],
  ['hires','Количество принятых работников'],
  ['hiringEfficiency','% исполнения плана по принятым кандидатам']
] as const;
const debtsterColumns=[
  ['staffPositionsCount','Штат'],
  ['vacantPositionsCount','Количество открытых вакансий'],
  ['traineesCount','Количество кандидатов на стажировке'],
  ['plannedDismissalsCount','Планируемый резерв']
] as const;
const rpColumns=[
  ['office','РП'],
  ['staffPositionsCount','Штат'],
  ['vacantPositionsCount','Количество открытых вакансий'],
  ['invitedCandidates','Количество приглашенных кандидатов'],
  ['invitationEfficiency','% исполнения плана по приглашенным кандидатам'],
  ['interviewedCandidates','Количество прошедших собеседование'],
  ['traineesCount','Количество кандидатов на стажировке'],
  ['plannedDismissalsCount','Планируемый резерв'],
  ['reserveCandidates','Количество кандидатов в резерве'],
  ['hires','Количество принятых работников'],
  ['hiringEfficiency','% исполнения плана по принятым кандидатам']
] as const;
let columnWidths:Record<string,number>=JSON.parse(localStorage.getItem('hr-column-widths-v2')||'{}');
type ReportColumn=readonly [string,string];
const isMainReport=()=>currentPage==='main-report';
const debtsterColumnIds=new Set<string>(debtsterColumns.map(([id])=>id));
const reportColumns=():readonly ReportColumn[]=>{const columns:readonly ReportColumn[]=isMainReport()?allColumns:rpColumns;return manager()?[...columns,['responsibles','Назначенные'] as const]:columns};

function esc(v:unknown){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!))}
let tooltipTarget:HTMLElement|null=null,tooltipTimer=0;
function hideTooltip(){clearTimeout(tooltipTimer);tooltipTarget=null;appTooltip.classList.remove('show')}
function placeTooltip(e:PointerEvent){const gap=14,box=appTooltip.getBoundingClientRect();let left=e.clientX+gap,top=e.clientY+gap;if(left+box.width>innerWidth-8)left=e.clientX-box.width-gap;if(top+box.height>innerHeight-8)top=e.clientY-box.height-gap;appTooltip.style.left=Math.max(8,left)+'px';appTooltip.style.top=Math.max(8,top)+'px'}
document.addEventListener('pointerover',e=>{const el=(e.target as HTMLElement).closest<HTMLElement>('.sheet [data-tooltip]');if(!el)return;const text=el.dataset.tooltip||'';if(!text)return;clearTimeout(tooltipTimer);tooltipTarget=el;appTooltip.textContent=text;placeTooltip(e);tooltipTimer=window.setTimeout(()=>{if(tooltipTarget===el)appTooltip.classList.add('show')},320)});
document.addEventListener('pointermove',e=>{if(tooltipTarget)placeTooltip(e)});
document.addEventListener('pointerout',e=>{if(!tooltipTarget)return;const next=e.relatedTarget as Node|null;if(!next||!tooltipTarget.contains(next))hideTooltip()});
document.addEventListener('scroll',()=>{hideTooltip();closeDatePicker()},true);
async function api<T=any>(url:string,options:RequestInit={}):Promise<T>{const res=await fetch(url,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(options.headers||{})}});if(!res.ok){let msg=`Ошибка ${res.status}`;try{msg=(await res.json()).error||msg}catch{}throw new Error(msg)}return res.status===204?null as T:res.json()}
let toastTimer=0;
function toast(message:string,error=false){
 const e=document.querySelector<HTMLElement>('#toast')!,duration=error?5200:3400;
 clearTimeout(toastTimer);e.className='toast';void e.offsetWidth;
 e.style.setProperty('--toast-duration',duration+'ms');e.setAttribute('role',error?'alert':'status');
 e.innerHTML=`<span class="toast-icon" aria-hidden="true">${error?icon('<circle cx="12" cy="12" r="9"/><path d="M12 7v6M12 17h.01"/>'):icons.check}</span><span class="toast-content"><strong>${error?'Ошибка':'Готово'}</strong><span>${esc(message)}</span></span><button class="toast-close" type="button" aria-label="Закрыть уведомление">×</button><span class="toast-progress" aria-hidden="true"></span>`;
 e.className='toast show'+(error?' error':' success');
 e.querySelector<HTMLButtonElement>('.toast-close')!.onclick=()=>{clearTimeout(toastTimer);e.classList.remove('show')};
 toastTimer=window.setTimeout(()=>e.classList.remove('show'),duration);
}
function setHeader(h:string,s:string){title.textContent=h;subtitle.textContent=s}
function drawNav(){
  const groups=[{label:'Работа с отчётами',ids:['report','main-report','trainee-reports','exports']},{label:'Управление',ids:['users','offices','main-offices']}];
  nav.innerHTML=groups.map(group=>{
    const items=pages.filter(([id])=>group.ids.includes(id));
    if(!items.length)return '';
    return `<div class="nav-group"><div class="nav-group-title">${group.label}</div>${items.map(([id,itemIcon,label])=>{
      const badge=id==='report'?'РП':id==='main-report'?'ГО':'';
      const displayLabel=badge?'Ежедневный отчёт':id==='main-offices'?'Главный офис':label;
      return `<button type="button" class="nav-item ${id===currentPage?'active':''}" data-page="${id}"${id===currentPage?' aria-current="page"':''}><span class="nav-icon">${itemIcon}</span><span class="nav-label">${displayLabel}</span>${badge?`<span class="nav-badge">${badge}</span>`:''}</button>`;
    }).join('')}</div>`;
  }).join('');
  nav.querySelectorAll<HTMLButtonElement>('[data-page]').forEach(b=>b.onclick=()=>{
    currentPage=b.dataset.page!;drawNav();nav.querySelector<HTMLButtonElement>(`[data-page="${currentPage}"]`)?.focus({preventScroll:true});route();
  });
}
async function route(){closeDatePicker();const reportView=currentPage==='report'||currentPage==='main-report'||currentPage==='trainee-reports';if(currentPage!=='report')stopDebtsterRefresh();content.classList.toggle('report-workspace',reportView);document.body.classList.toggle('report-page',reportView);if(currentPage!=='report'&&currentPage!=='main-report'&&reportSocket){const old=reportSocket;reportSocket=null;old.close()}content.innerHTML='<div class="empty">Загрузка…</div>';try{if(currentPage==='report'||currentPage==='main-report')await loadReport();else if(currentPage==='trainee-reports')await traineeReportsPage();else if(currentPage==='exports')await exportPage();else if(currentPage==='users')await usersPage();else if(currentPage==='offices')await officesPage();else if(currentPage==='main-offices')await mainOfficesPage()}catch(e){content.innerHTML=`<div class="card empty">${esc((e as Error).message)}</div>`;scheduleDebtsterRefresh()}}

const numeric:[keyof Row,string][]=[['openVacancies','Количество открытых вакансий'],['invitedCandidates','Количество приглашенных кандидатов'],['interviewedCandidates','Количество прошедших собеседование'],['interns','Количество кандидатов на стажировке'],['plannedReserve','Планируемый резерв'],['reserveCandidates','Количество кандидатов в резерве']];
const peopleFields:Record<PeopleKey,{category:PeopleCategory;title:string;itemTitle:string;action:string}>={
 invitedCandidates:{category:'invited_candidates',title:'Количество приглашенных кандидатов',itemTitle:'Приглашённые кандидаты',action:'Кого пригласили'},
 interviewedCandidates:{category:'interviewed_candidates',title:'Количество прошедших собеседование',itemTitle:'Кандидаты, прошедшие собеседование',action:'Кто прошёл собеседование'},
 interns:{category:'interns',title:'Количество кандидатов на стажировке',itemTitle:'Кандидаты на стажировке',action:'Кого направили на стажировку'},
 reserveCandidates:{category:'reserve_candidates',title:'Количество кандидатов в резерве',itemTitle:'Кандидаты в резерве',action:'Кого добавили в резерв'},
 dismissedWorkers:{category:'dismissed_workers',title:'Количество уволенных работников',itemTitle:'Уволенные работники',action:'Кого уволили'}
};
function isPeopleKey(key:keyof Row|string):key is PeopleKey{return key in peopleFields}
function manager(){return currentUser?.role==='admin'||currentUser?.role==='superadmin'}
function stopDebtsterRefresh(){clearTimeout(debtsterRefreshTimer);debtsterRefreshTimer=0}
function scheduleDebtsterRefresh(delay=debtsterRefreshInterval){stopDebtsterRefresh();if(!currentUser||currentPage!=='report'||document.visibilityState!=='visible')return;debtsterRefreshTimer=window.setTimeout(refreshDebtsterReport,delay)}
async function refreshDebtsterReport(){debtsterRefreshTimer=0;if(!currentUser||currentPage!=='report'||document.visibilityState!=='visible')return;if(dirtyRows.size||modalRoot.childElementCount){scheduleDebtsterRefresh(debtsterRefreshRetry);return}try{await loadReport()}catch{scheduleDebtsterRefresh()}}
async function loadReport(){const main=isMainReport();setHeader(main?'Ежедневный отчет':manager()?'Сводный отчёт':'Мой ежедневный отчёт',main?'Ежедневные показатели компаний':manager()?'Суммарные показатели сотрудников':'Заполнение персональных показателей');rememberScroll();if(manager()){adminUsers=await api<User[]>(`/api/users?context=report&date=${encodeURIComponent(reportDate)}`);if(selectedEmployee&&!adminUsers.some(user=>user.id===selectedEmployee))selectedEmployee=''}const filter=manager()&&selectedEmployee?`&employeeId=${encodeURIComponent(selectedEmployee)}`:'';report=await api(`${main?'/api/main-office/bootstrap':'/api/bootstrap'}?date=${reportDate}${filter}`);renderReport();scheduleDebtsterRefresh()}
function traineeDate(value:string|null){return value&&/^\d{4}-\d{2}-\d{2}$/.test(value)?displayDate(value):'—'}
function traineeRowClass(row:TraineeReport){
 const source=row.source.trim().toUpperCase();
 if(!Array.isArray(row.matches))return '';
 if(source==='ДИР'&&row.matches.length)return 'trainee-director-match';
 if(source==='ОК'&&row.matches.length===0)return 'trainee-ok-unmatched';
 return '';
}
function traineeSearchResults(row:TraineeReport){
 if(!Array.isArray(row.matches))return '<td class="trainee-search-result-cell">Поиск недоступен</td>';
 if(!row.matches.length)return '<td class="trainee-search-result-cell">Не найдено</td>';
 return `<td class="trainee-search-result-cell"><ul class="trainee-matches" aria-label="Возможные совпадения в нашей базе">${row.matches.map(match=>`<li><span>${esc(match.full_name)}</span><small aria-label="Сходство ФИО: ${esc(match.score)}%">${esc(match.score)}%</small></li>`).join('')}</ul></td>`;
}
async function traineeReportsPage(){
 setHeader('Отчеты по стажерам','Актуальные данные по стажерам подразделений');
 const rows=await api<TraineeReport[]>(`/api/trainees?report_date=${encodeURIComponent(reportDate)}`);
 const cell=(value:unknown,className='',tooltip='')=>`<td class="${className}" ${tooltip?`data-tooltip="${esc(tooltip)}"`:''}>${value===null||value===undefined||value===''?'—':esc(value)}</td>`;
 content.innerHTML=`<div class="toolbar trainee-toolbar"><div class="date-switcher"><button class="btn icon-btn" id="prev-day" aria-label="Предыдущий рабочий день">${icons.left}</button><button class="report-date-button" id="report-date" type="button" aria-haspopup="dialog" aria-label="Выбрать дату отчёта"><span>${displayDate(reportDate)}</span>${icons.calendar}</button><button class="btn icon-btn" id="next-day" aria-label="Следующий рабочий день">${icons.right}</button></div><span class="trainee-count">Стажеров: <b>${rows.length}</b></span><div class="spacer"></div></div>
 <div class="sheet-wrap trainee-sheet-wrap"><table class="sheet trainee-sheet"><colgroup><col class="trainee-number"><col class="trainee-department"><col class="trainee-name"><col class="trainee-source"><col class="trainee-date"><col class="trainee-search-result"></colgroup><thead><tr><th>№</th><th>РП</th><th>Стажер</th><th>Источник</th><th>Дата собеседования</th><th>Результат поиска<small class="trainee-search-hint">Возможные совпадения · сходство ФИО</small></th></tr></thead><tbody>${rows.length?rows.map((row,index)=>`<tr class="${traineeRowClass(row)}">${cell(index+1,'trainee-number-cell')}${cell(row.department,'primary-trainee-cell',row.department)}${cell(row.full_name,'primary-trainee-cell',row.full_name)}${cell(row.source)}${cell(traineeDate(row.interview_date))}${traineeSearchResults(row)}</tr>`).join(''):`<tr><td class="trainee-table-empty" colspan="6">За ${displayDate(reportDate)} данных по стажерам нет</td></tr>`}</tbody></table></div>`;
 const dateButton=content.querySelector<HTMLButtonElement>('#report-date')!;dateButton.onclick=()=>openDatePicker(dateButton);
 content.querySelector<HTMLButtonElement>('#prev-day')!.onclick=()=>shiftDate(-1);content.querySelector<HTMLButtonElement>('#next-day')!.onclick=()=>shiftDate(1);
 wireSheetHighlighting();restoreScroll()
}
function reportEmployeeOptions(){const option=(u:User)=>`<option value="${u.id}" ${u.id===selectedEmployee?'selected':''}>${esc([u.lastName,u.firstName,u.middleName].filter(Boolean).join(' '))}</option>`;return `<option value="">Все сотрудники</option>${adminUsers.map(option).join('')}`}
function colClass(_id:string){return ''}
function defaultTableWidth(){return Math.max(reportColumns().length*80,Math.min(1470,content.clientWidth-24))}
function defaultColWidth(id:string){const columns=reportColumns(),index=columns.findIndex(([column])=>column===id),natural=columns.reduce<number>((sum,[column])=>sum+(defaultColumnWidths[column]||125),0),target=defaultTableWidth();if(index<0)return 125;const before=columns.slice(0,index).reduce<number>((sum,[column])=>sum+(defaultColumnWidths[column]||125),0),after=before+(defaultColumnWidths[id]||125);return Math.round(after*target/natural)-Math.round(before*target/natural)}
function colWidth(id:string){return columnWidths[id]??defaultColWidth(id)}
function tableWidth(){return reportColumns().reduce<number>((width,[id])=>width+colWidth(id),0)}
function hasCustomColumnWidths(){return reportColumns().some(([id])=>columnWidths[id]!==undefined&&columnWidths[id]!==defaultColWidth(id))}
function updateResetButtonVisibility(){const button=content.querySelector<HTMLButtonElement>('#reset-column-widths');if(button)button.hidden=!hasCustomColumnWidths()}
function alignTableWithToolbar(){const toolbar=content.querySelector<HTMLElement>('.toolbar'),wrap=content.querySelector<HTMLElement>('.sheet-wrap'),table=content.querySelector<HTMLTableElement>('.sheet');if(!toolbar||!wrap||!table)return;table.style.marginLeft=Math.max(0,toolbar.getBoundingClientRect().left-wrap.getBoundingClientRect().left)+'px'}
function headerCell(id:string,label:string){return `<th data-col="${id}"><span>${esc(label)}</span><span class="col-resizer" data-resize="${id}"></span></th>`}
function contributionTooltip(r:Row,key:string,total:number,percent=false){if(!manager())return '';const value=percent?total.toFixed(1)+'%':String(total);if(key==='openVacancies'||key==='plannedReserve')return `Итого: ${value}\nОбщее значение для всех сотрудников`;const values=r.contributions?.[key]||[],details=values.length?values.map(x=>`${x.name || 'Сотрудник'} — ${percent?x.value.toFixed(1)+'%':x.value}`).join('\n'):'Нет заполненных отчётов';return `Итого: ${value}\n${details}`}
function planEfficiencyCell(r:Row,kind:'invitation'|'hiring'){const invited=kind==='invitation',value=invited?r.invitationEfficiency:r.hiringEfficiency,plan=invited?r.invitationPlan:r.hiringPlan,actual=invited?r.invitedCandidates:r.hiredWorkers.length,key=invited?'invitationEfficiency':'hiringEfficiency',label=invited?'Приглашено':'Принято';const tooltip=manager()?contributionTooltip(r,key,value,true):`План: ${plan}\n${label}: ${actual}`;return `<span class="readonly-cell plan-efficiency" data-tooltip="${esc(tooltip)}">${value.toFixed(1)}%</span>`}
function hiredCell(r:Row,locked:boolean){if(!locked)return `<button class="cell nav-cell people hires">${r.hiredWorkers.length||0}</button>`;if(manager())return `<button class="cell people hires summary-hires">${r.hiredWorkers.length||0}</button>`;return `<span class="readonly-cell">${r.hiredWorkers.length}</span>`}
function peopleCell(r:Row,key:PeopleKey,locked:boolean){const value=Number(r[key]||0);if(!locked)return `<button class="cell nav-cell people people-list" data-people-key="${key}">${value}</button>`;if(manager())return `<button class="cell people people-list summary-hires" data-people-key="${key}">${value}</button>`;return `<span class="readonly-cell">${value}</span>`}
function valueWithChange(value:number,change:number){return `<span class="trainee-value">${value}${change?`<span class="trainee-change">(${change>0?'+':''}${change})</span>`:''}</span>`}
function debtsterCell(r:Row,key:string,unassigned=false){const value=Number((r as any)[key]||0);if(key==='plannedDismissalsCount'&&!unassigned)return `<button class="cell people summary-hires planned-dismissals" type="button">${value}</button>`;if(key==='traineesCount')return `<span class="readonly-cell">${valueWithChange(value,Number(r.traineesCountChange||0))}</span>`;return `<span class="readonly-cell">${value}</span>`}
function wireSheetHighlighting(){
 const table=content.querySelector<HTMLTableElement>('.sheet');if(!table)return;
 let hoveredColumn='';
 const markColumn=(column:string,className:string,on:boolean)=>table.querySelectorAll<HTMLElement>(`[data-col="${column}"]`).forEach(cell=>cell.classList.toggle(className,on));
 const setHoveredColumn=(column:string)=>{if(column===hoveredColumn)return;if(hoveredColumn)markColumn(hoveredColumn,'hovered-column',false);hoveredColumn=column;if(column)markColumn(column,'hovered-column',true)};
 table.addEventListener('pointerover',event=>{const cell=(event.target as HTMLElement).closest<HTMLElement>('tbody td[data-col]');setHoveredColumn(cell?.dataset.col||'')});
 table.addEventListener('pointerleave',()=>setHoveredColumn(''));
 table.addEventListener('focusin',event=>{const cell=(event.target as HTMLElement).closest<HTMLElement>('td[data-col]');if(!cell)return;table.querySelectorAll('.active-column').forEach(el=>el.classList.remove('active-column'));markColumn(cell.dataset.col!,'active-column',true)});
 table.addEventListener('focusout',()=>requestAnimationFrame(()=>{const focused=document.activeElement as HTMLElement|null;if(focused&&table.contains(focused))return;table.querySelectorAll('.active-column').forEach(el=>el.classList.remove('active-column'))}));
}
function reportBodyCell(r:Row,rowLocked:boolean,id:string){if(id==='office')return `<td data-col="office" class="${colClass('office')}">${esc(r.officeName)}</td>`;if(id==='responsibles')return `<td data-col="responsibles"><button class="cell people summary-hires responsible-cell" type="button">${r.responsibleCount||0}</button></td>`;if(debtsterColumnIds.has(id))return `<td data-col="${id}">${debtsterCell(r,id,!isMainReport()&&!manager()&&!r.assigned)}</td>`;if(id==='hires')return `<td data-col="hires" class="${colClass('hires')}" data-tooltip="${esc(contributionTooltip(r,'hiredWorkers',r.hiredWorkers.length))}">${hiredCell(r,rowLocked)}</td>`;if(id==='invitationEfficiency')return `<td data-col="invitationEfficiency">${planEfficiencyCell(r,'invitation')}</td>`;if(id==='hiringEfficiency')return `<td data-col="hiringEfficiency">${planEfficiencyCell(r,'hiring')}</td>`;const key=id as keyof Row,value=Number(r[key]||0);return `<td data-col="${id}" class="${colClass(id)}" data-tooltip="${esc(contributionTooltip(r,id,value))}">${isPeopleKey(id)?peopleCell(r,id,rowLocked):`<input class="cell nav-cell" type="text" inputmode="numeric" pattern="[0-9]*" data-key="${id}" data-original="${value}" value="${value}" ${rowLocked?'disabled':''}>`}</td>`}
function reportTotalCell(id:string){if(id==='office')return `<td data-col="office" class="${colClass('office')}">ИТОГО</td>`;if(id==='responsibles')return '<td data-col="responsibles"></td>';if(id==='invitationEfficiency'||id==='hiringEfficiency')return `<td data-col="${id}" data-total="${id}">0.0%</td>`;const total=id==='hires'?'hiredWorkers':id;return `<td data-col="${id}" class="${colClass(id)}" data-total="${total}">0</td>`}
function dailyPlanSummary(){if(!report)return '';const invited=report.rows.reduce((sum,row)=>sum+row.invitedCandidates,0),hired=report.rows.reduce((sum,row)=>sum+row.hiredWorkers.length,0),editable=manager(),tag=editable?'button':'div',attrs=editable?' id="daily-plan-summary" type="button" title="Изменить планы на выбранный день"':'';return `<${tag} class="daily-plan-summary${editable?'':' is-readonly'}"${attrs}><span>План по пригл.: <b><i data-plan-actual="invited">${invited}</i>/${report.invitationPlan}</b></span><i class="daily-plan-divider" aria-hidden="true"></i><span>План по прин.: <b><i data-plan-actual="hired">${hired}</i>/${report.hiringPlan}</b></span></${tag}>`}
function renderReport(){if(!report)return;const main=isMainReport(),columns=reportColumns(),locked=!report.report.editable,filtered=adminUsers.find(x=>x.id===selectedEmployee),isPast=reportDate<today(),isFuture=reportDate>today(),accessCount=report.report.accessCount||0;const accessButton=manager()&&reportDate!==today()?`<button class="btn btn-outline with-icon report-access-button ${accessCount?'has-access':''}" id="report-access" ${isFuture?'disabled title="Доступ нельзя открыть до наступления выбранной даты"':''}>${icons.access}<span>${accessCount?`Доступ открыт · ${accessCount}`:'Открыть доступ'}</span></button>`:'';content.innerHTML=`
 <div class="toolbar"><div class="date-switcher"><button class="btn icon-btn" id="prev-day" aria-label="Предыдущий рабочий день">${icons.left}</button><button class="report-date-button" id="report-date" type="button" aria-haspopup="dialog" aria-label="Выбрать дату отчёта"><span>${displayDate(reportDate)}</span>${icons.calendar}</button><button class="btn icon-btn" id="next-day" aria-label="Следующий рабочий день">${icons.right}</button></div>${manager()?`<select id="employee-filter">${reportEmployeeOptions()}</select>`:''}${dailyPlanSummary()}${locked&&!manager()?'<span class="readonly-note">Доступ закрыт</span>':''}${!locked?'<span id="save-state" class="save-state saved">Сохранено</span>':''}<div class="spacer"></div>${accessButton}<button class="btn btn-outline icon-btn" id="reset-column-widths" title="Сбросить ширину колонок" aria-label="Сбросить ширину колонок" ${hasCustomColumnWidths()?'':'hidden'}>${icons.reset}</button></div>
 <div class="sheet-wrap"><table class="sheet ${manager()?'manager-sheet':''}" style="width:${tableWidth()}px"><colgroup>${columns.map(([id])=>`<col data-col="${id}" class="${colClass(id)}" style="width:${colWidth(id)}px">`).join('')}</colgroup><thead><tr>${columns.map(([id,label])=>headerCell(id,main&&id==='office'?'Компания':label)).join('')}</tr></thead><tbody>
 ${report.rows.map((r,ri)=>{const unassigned=!main&&!manager()&&!r.assigned,rowLocked=locked||!r.id||unassigned;return `<tr data-row="${ri}" class="${unassigned?'unassigned-row':''}" ${unassigned?'title="РП не назначен сотруднику"':''}>${columns.map(([id])=>reportBodyCell(r,rowLocked,id)).join('')}</tr>`}).join('')}</tbody><tfoot><tr>${columns.map(([id])=>reportTotalCell(id)).join('')}</tr></tfoot></table></div>`;
 const dateButton=document.querySelector<HTMLButtonElement>('#report-date')!;dateButton.onclick=()=>openDatePicker(dateButton);
 document.querySelector<HTMLButtonElement>('#prev-day')!.onclick=()=>shiftDate(-1);document.querySelector<HTMLButtonElement>('#next-day')!.onclick=()=>shiftDate(1);
 document.querySelector<HTMLButtonElement>('#reset-column-widths')!.onclick=resetColumnWidths;
 const access=document.querySelector<HTMLButtonElement>('#report-access');if(access&&isPast)access.onclick=reportAccessModal;
 const employeeFilter=document.querySelector<HTMLSelectElement>('#employee-filter');if(employeeFilter)employeeFilter.onchange=()=>{selectedEmployee=employeeFilter.value;loadReport()};
 const dailyPlan=document.querySelector<HTMLButtonElement>('#daily-plan-summary');if(dailyPlan)dailyPlan.onclick=dailyPlanModal;
 content.querySelectorAll<HTMLTableRowElement>('tbody tr').forEach(tr=>{const i=Number(tr.dataset.row),r=report!.rows[i];tr.querySelectorAll<HTMLInputElement>('input[data-key]:not(:disabled)').forEach(inp=>wireNumericInput(inp,r,tr));const hires=tr.querySelector<HTMLButtonElement>('.hires');if(hires)hires.onclick=()=>manager()&&locked?hiredSummaryModal(r):hiresModal(r,tr);const responsible=tr.querySelector<HTMLButtonElement>('.responsible-cell');if(responsible)responsible.onclick=()=>responsiblesModal(r,responsible);const dismissals=tr.querySelector<HTMLButtonElement>('.planned-dismissals');if(dismissals)dismissals.onclick=()=>plannedDismissalsModal(r);tr.querySelectorAll<HTMLButtonElement>('.people-list').forEach(button=>{const key=button.dataset.peopleKey as PeopleKey;button.onclick=()=>manager()&&locked?peopleSummaryModal(r,key):peopleModal(r,tr,key)});tr.querySelectorAll<HTMLElement>('.nav-cell').forEach(x=>{x.addEventListener('focus',()=>tr.classList.add('active-row'));x.addEventListener('blur',()=>{if(!tr.contains(document.activeElement))tr.classList.remove('active-row')})})});wireSheetHighlighting();keyboardNav();setupColumnResizing();alignTableWithToolbar();recalc();restoreScroll();connectReportSocket()}
function fullName(e:Employee){return [e.lastName,e.firstName,e.middleName].filter(Boolean).join(' ')}
function recalc(){if(!report)return;const keys=numeric.map(x=>x[0]);keys.forEach(k=>{const n=report!.rows.reduce((s,r)=>s+Number(r[k]||0),0);const el=content.querySelector(`[data-total="${k}"]`);if(el)el.textContent=String(n)});if(!isMainReport())debtsterColumns.forEach(([key])=>{const n=report!.rows.reduce((sum,row)=>sum+Number((row as any)[key]||0),0),el=content.querySelector<HTMLElement>(`[data-total="${key}"]`);if(!el)return;if(key==='traineesCount'){const change=report!.rows.reduce((sum,row)=>sum+Number(row.traineesCountChange||0),0);el.innerHTML=valueWithChange(n,change)}else el.textContent=String(n)});const invited=report.rows.reduce((s,r)=>s+r.invitedCandidates,0),hires=report.rows.reduce((s,r)=>s+r.hiredWorkers.length,0);content.querySelector('[data-total="hiredWorkers"]')!.textContent=String(hires);const invitationEfficiency=content.querySelector('[data-total="invitationEfficiency"]'),hiringEfficiency=content.querySelector('[data-total="hiringEfficiency"]');if(invitationEfficiency)invitationEfficiency.textContent=(report.invitationPlan?invited*100/report.invitationPlan:0).toFixed(1)+'%';if(hiringEfficiency)hiringEfficiency.textContent=(report.hiringPlan?hires*100/report.hiringPlan:0).toFixed(1)+'%';const invitedActual=content.querySelector('[data-plan-actual="invited"]'),hiredActual=content.querySelector('[data-plan-actual="hired"]');if(invitedActual)invitedActual.textContent=String(invited);if(hiredActual)hiredActual.textContent=String(hires)}
function rowPayload(r:Row){return{openVacancies:r.openVacancies,plannedReserve:r.plannedReserve,invitedCandidates:r.invitedCandidates,interviewedCandidates:r.interviewedCandidates,interns:r.interns,reserveCandidates:r.reserveCandidates,dismissedWorkers:r.dismissedWorkers,responsibleIds:[],hiredWorkers:r.hiredWorkers,people:r.people||{}}}
function setSaveState(state:'saving'|'saved'|'failed',message?:string){const el=content.querySelector<HTMLElement>('#save-state');if(!el)return;el.className=`save-state ${state}`;el.textContent=message||(state==='saving'?'Сохранение...':state==='saved'?'Сохранено':'Ошибка сохранения')}
function scheduleSave(r:Row,tr:HTMLTableRowElement){dirtyRows.add(r.id);setSaveState('saving');clearTimeout(saveTimers.get(r.id));saveTimers.set(r.id,window.setTimeout(()=>saveRow(r,tr),500))}
function updateEfficiencyCells(r:Row,tr:HTMLTableRowElement){r.invitationEfficiency=r.invitationPlan?100*r.invitedCandidates/r.invitationPlan:0;r.hiringEfficiency=r.hiringPlan?100*r.hiredWorkers.length/r.hiringPlan:0;const invited=tr.querySelector<HTMLElement>('[data-col="invitationEfficiency"] .plan-efficiency'),hired=tr.querySelector<HTMLElement>('[data-col="hiringEfficiency"] .plan-efficiency');if(invited)invited.textContent=r.invitationEfficiency.toFixed(1)+'%';if(hired)hired.textContent=r.hiringEfficiency.toFixed(1)+'%'}
async function saveRow(r:Row,tr:HTMLTableRowElement){clearTimeout(saveTimers.get(r.id));saveTimers.delete(r.id);setSaveState('saving');try{const x=await api<{efficiency:number;invitationEfficiency:number;hiringEfficiency:number}>(`${isMainReport()?'/api/main-office/report/rows':'/api/report/rows'}/${r.id}`,{method:'PUT',body:JSON.stringify(rowPayload(r))});r.efficiency=x.efficiency;r.invitationEfficiency=x.invitationEfficiency;r.hiringEfficiency=x.hiringEfficiency;updateEfficiencyCells(r,tr);dirtyRows.delete(r.id);tr.querySelectorAll<HTMLInputElement>('input[data-key]').forEach(i=>{i.dataset.original=i.value||'0';i.classList.remove('invalid')});setSaveState(dirtyRows.size?'saving':'saved')}catch(e){const message=(e as Error).message;setSaveState('failed',message);tr.querySelectorAll<HTMLInputElement>('input[data-key]').forEach(i=>i.classList.add('invalid'));toast(message,true)}}
async function completeReport(){if(!report)return;try{await Promise.all(report.rows.filter(r=>dirtyRows.has(r.id)).map(r=>{const tr=content.querySelector<HTMLTableRowElement>(`tr[data-row="${report!.rows.indexOf(r)}"]`)!;return saveRow(r,tr)}));await api(`/api/reports/${report.report.id}/complete`,{method:'POST',body:'{}'});toast('Отчёт успешно завершён');await loadReport()}catch(e){toast((e as Error).message,true)}}
function wireNumericInput(inp:HTMLInputElement,r:Row,tr:HTMLTableRowElement){inp.onfocus=()=>{inp.dataset.original=inp.value;if(inp.value==='0')inp.value='';else inp.select();tr.classList.add('active-row')};inp.onbeforeinput=e=>{const ev=e as InputEvent;if(ev.data&&!/^\d+$/.test(ev.data))e.preventDefault()};inp.onpaste=e=>{const text=e.clipboardData?.getData('text')||'';if(!/^\d+$/.test(text.trim())){e.preventDefault();inp.classList.add('invalid');toast('Разрешены только целые неотрицательные числа',true);setTimeout(()=>inp.classList.remove('invalid'),1200)}};inp.oninput=()=>{const clean=inp.value.replace(/[^0-9]/g,'');if(inp.value!==clean){inp.value=clean;inp.classList.add('invalid')}else inp.classList.remove('invalid');(r as any)[inp.dataset.key!]=clean===''?0:Number(clean);updateEfficiencyCells(r,tr);recalc();scheduleSave(r,tr)};inp.onblur=()=>{if(inp.value===''){inp.value='0';(r as any)[inp.dataset.key!]=0}if(!tr.contains(document.activeElement))tr.classList.remove('active-row')}}
function keyboardNav(){const cells=[...content.querySelectorAll<HTMLElement>('.nav-cell')].filter(x=>x.offsetParent!==null&&!('disabled' in x&&(x as HTMLInputElement).disabled));const perRow=report?cells.length/report.rows.length:1;cells.forEach((c,i)=>c.onkeydown=e=>{if(e.key==='Escape'&&c instanceof HTMLInputElement){e.preventDefault();c.value=c.dataset.original||'0';const tr=c.closest<HTMLTableRowElement>('tr')!,r=report!.rows[Number(tr.dataset.row)];(r as any)[c.dataset.key!]=Number(c.value);clearTimeout(saveTimers.get(r.id));dirtyRows.delete(r.id);recalc();c.blur();setSaveState(dirtyRows.size?'saving':'saved');return}let next=-1;if(e.key==='Enter'){e.preventDefault();const tr=c.closest<HTMLTableRowElement>('tr')!,r=report!.rows[Number(tr.dataset.row)];void saveRow(r,tr);next=i+1}else if(e.key==='ArrowRight')next=i+1;else if(e.key==='ArrowLeft')next=i-1;else if(e.key==='ArrowDown')next=i+perRow;else if(e.key==='ArrowUp')next=i-perRow;if(next>=0&&next<cells.length){e.preventDefault();cells[next].focus();if(cells[next] instanceof HTMLInputElement)(cells[next] as HTMLInputElement).select()}})}

function closeDatePicker(){datePickerRoot.innerHTML='';if(datePickerOutsideHandler){document.removeEventListener('pointerdown',datePickerOutsideHandler);datePickerOutsideHandler=null}if(datePickerKeyHandler){document.removeEventListener('keydown',datePickerKeyHandler);datePickerKeyHandler=null}}
function openDatePicker(anchor:HTMLElement){
 closeDatePicker();let month=dateObject(reportDate);month=new Date(month.getFullYear(),month.getMonth(),1,12);
 const draw=()=>{const year=month.getFullYear(),monthIndex=month.getMonth(),first=new Date(year,monthIndex,1,12),days=new Date(year,monthIndex+1,0,12).getDate(),offset=(first.getDay()+6)%7,total=Math.ceil((offset+days)/7)*7,monthTitle=month.toLocaleDateString('ru-RU',{month:'long',year:'numeric'});let cells='';for(let index=0;index<total;index++){const day=index-offset+1;if(day<1||day>days){cells+='<span class="calendar-empty"></span>';continue}const value=dateValue(new Date(year,monthIndex,day,12)),weekend=isWeekend(value);cells+=`<button class="calendar-day ${weekend?'weekend':''} ${value===reportDate?'selected':''} ${value===today()?'current':''}" type="button" data-date="${value}" ${weekend?'disabled aria-label="Выходной день"':''}>${day}</button>`}datePickerRoot.innerHTML=`<div class="date-picker" role="dialog" aria-label="Выбор даты отчёта"><div class="calendar-head"><button type="button" class="calendar-nav calendar-prev" aria-label="Предыдущий месяц">${icons.left}</button><strong>${esc(monthTitle)}</strong><button type="button" class="calendar-nav calendar-next" aria-label="Следующий месяц">${icons.right}</button></div><div class="calendar-weekdays"><span>Пн</span><span>Вт</span><span>Ср</span><span>Чт</span><span>Пт</span><span class="weekend">Сб</span><span class="weekend">Вс</span></div><div class="calendar-grid">${cells}</div><div class="calendar-foot"><span><i></i>Сегодня</span><small>Сб и Вс — выходные</small></div></div>`;const picker=datePickerRoot.firstElementChild as HTMLElement,rect=anchor.getBoundingClientRect(),width=picker.offsetWidth||304,left=Math.max(8,Math.min(rect.left,innerWidth-width-8)),height=picker.offsetHeight||360,top=rect.bottom+6+height>innerHeight?Math.max(8,rect.top-height-6):rect.bottom+6;picker.style.left=left+'px';picker.style.top=top+'px';picker.querySelector<HTMLButtonElement>('.calendar-prev')!.onclick=()=>{month=new Date(year,monthIndex-1,1,12);draw()};picker.querySelector<HTMLButtonElement>('.calendar-next')!.onclick=()=>{month=new Date(year,monthIndex+1,1,12);draw()};picker.querySelectorAll<HTMLButtonElement>('.calendar-day:not(:disabled)').forEach(button=>button.onclick=()=>{const value=button.dataset.date!;closeDatePicker();changeDate(value)})};
 draw();requestAnimationFrame(()=>{datePickerOutsideHandler=event=>{if(!datePickerRoot.contains(event.target as Node)&&!anchor.contains(event.target as Node))closeDatePicker()};document.addEventListener('pointerdown',datePickerOutsideHandler!)});datePickerKeyHandler=event=>{if(event.key==='Escape'){event.preventDefault();closeDatePicker();anchor.focus()}};document.addEventListener('keydown',datePickerKeyHandler)
}
function changeDate(value:string){if(isWeekend(value))return;closeDatePicker();rememberScroll();reportDate=value;if(currentPage==='trainee-reports')traineeReportsPage();else loadReport()}
function shiftDate(days:number){const direction=days<0?-1:1,date=dateObject(reportDate);do{date.setDate(date.getDate()+direction)}while(date.getDay()===0||date.getDay()===6);changeDate(dateValue(date))}
function rememberScroll(){const el=content.querySelector<HTMLElement>('.sheet-wrap');if(el)sessionStorage.setItem(`hr-scroll-${reportDate}`,JSON.stringify({top:el.scrollTop,left:el.scrollLeft}))}
function restoreScroll(){requestAnimationFrame(()=>{const el=content.querySelector<HTMLElement>('.sheet-wrap');if(!el)return;const pos=JSON.parse(sessionStorage.getItem(`hr-scroll-${reportDate}`)||'{"top":0,"left":0}');el.scrollTop=pos.top;el.scrollLeft=pos.left;el.onscroll=()=>sessionStorage.setItem(`hr-scroll-${reportDate}`,JSON.stringify({top:el.scrollTop,left:el.scrollLeft}))})}
function connectReportSocket(){if(reportSocket){const old=reportSocket;reportSocket=null;old.close()}const socketDate=reportDate,main=isMainReport(),ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/reports?date=${encodeURIComponent(socketDate)}`);reportSocket=ws;ws.onmessage=e=>{const event=JSON.parse(e.data);if(event.date!==reportDate)return;if(event.type==='report_access_changed'){if(!manager()&&event.userIds?.includes(currentUser?.id))loadReport();return}if(event.type==='report_plan_changed'){const expected=main?'main_office':'rp';if(event.reportType===expected&&(manager()||event.userIds?.includes(currentUser?.id)))loadReport();return}if(event.type!==(main?'main_office_report_updated':'report_updated'))return;if(manager()){clearTimeout(reportRefreshTimer);reportRefreshTimer=window.setTimeout(()=>loadReport(),250);return}if((event.field==='openVacancies'||event.field==='plannedReserve')&&report){const index=report.rows.findIndex(r=>r.officeId===event.officeId);if(index<0)return;const row=report.rows[index],key=event.field as 'openVacancies'|'plannedReserve';row[key]=Number(event.value)||0;const input=content.querySelector<HTMLInputElement>(`tr[data-row="${index}"] input[data-key="${key}"]`);if(input){input.value=String(row[key]);input.dataset.original=input.value}recalc()}};ws.onclose=()=>{if(reportSocket===ws){reportSocket=null;if((currentPage==='report'||currentPage==='main-report')&&isMainReport()===main&&reportDate===socketDate)setTimeout(connectReportSocket,1500)}}}
function setupColumnResizing(){content.querySelectorAll<HTMLElement>('[data-resize]').forEach(handle=>handle.onpointerdown=e=>{e.preventDefault();const id=handle.dataset.resize!,col=content.querySelector<HTMLElement>(`col[data-col="${id}"]`)!,table=content.querySelector<HTMLTableElement>('.sheet')!,start=e.clientX,startWidth=col.getBoundingClientRect().width,startTableWidth=table.getBoundingClientRect().width;const move=(ev:PointerEvent)=>{const width=Math.round(Math.max(80,Math.min(320,startWidth+ev.clientX-start)));col.style.width=width+'px';table.style.width=startTableWidth+width-startWidth+'px';columnWidths[id]=width;updateResetButtonVisibility()};const up=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);if(hasCustomColumnWidths())localStorage.setItem('hr-column-widths-v2',JSON.stringify(columnWidths));else localStorage.removeItem('hr-column-widths-v2')};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up)})}
function applyColumnWidths(){content.querySelectorAll<HTMLElement>('col[data-col]').forEach(col=>{col.style.width=colWidth(col.dataset.col!)+'px'});const table=content.querySelector<HTMLTableElement>('.sheet');if(table)table.style.width=tableWidth()+'px';alignTableWithToolbar()}
function resetColumnWidths(){columnWidths={};localStorage.removeItem('hr-column-widths-v2');applyColumnWidths();updateResetButtonVisibility()}

async function dailyPlanModal(){
 try{
  const reportType=isMainReport()?'main_office':'rp',all=await api<DailyPlan[]>(`/api/daily-plans?date=${encodeURIComponent(reportDate)}&reportType=${reportType}`),plans=selectedEmployee?all.filter(item=>item.userId===selectedEmployee):all;
  if(!plans.length){toast('Сотрудники для изменения плана не найдены',true);return}
  const rows=plans.map(item=>`<div class="daily-plan-row"><span><b>${esc(item.name)}</b><small>${item.overridden?'Планы на этот день изменены':'Используются основные планы'}</small></span><label><small>Приглашённые</small><input class="input daily-plan-input" type="number" min="0" step="1" inputmode="numeric" data-kind="invited" data-user-id="${item.userId}" data-original="${item.invitedPlan}" value="${item.invitedPlan}"></label><label><small>Принятые</small><input class="input daily-plan-input" type="number" min="0" step="1" inputmode="numeric" data-kind="hired" data-user-id="${item.userId}" data-original="${item.hiredPlan}" value="${item.hiredPlan}"></label></div>`).join('');
  showModal(`Планы на ${displayDate(reportDate)}`,`<div class="modal-intro"><b>Однодневные планы кандидатов</b><span>Изменения действуют только для выбранной даты и не меняют основные планы сотрудника.</span></div><div class="daily-plan-list">${rows}</div>`,async()=>{
   const changed=plans.filter(item=>[...document.querySelectorAll<HTMLInputElement>(`.daily-plan-input[data-user-id="${item.userId}"]`)].some(input=>input.value!==input.dataset.original)).map(item=>({userId:item.userId,invitedPlan:Number((document.querySelector(`.daily-plan-input[data-user-id="${item.userId}"][data-kind="invited"]`) as HTMLInputElement).value),hiredPlan:Number((document.querySelector(`.daily-plan-input[data-user-id="${item.userId}"][data-kind="hired"]`) as HTMLInputElement).value)}));
   if(changed.some(item=>!Number.isInteger(item.invitedPlan)||item.invitedPlan<0||!Number.isInteger(item.hiredPlan)||item.hiredPlan<0)){toast('Планы должны быть целыми неотрицательными числами',true);return}
   if(!changed.length){closeModal();return}
   await api('/api/daily-plans',{method:'PUT',body:JSON.stringify({date:reportDate,reportType,plans:changed})});closeModal();toast('План на выбранный день сохранён');await loadReport()
  })
 }catch(error){toast((error as Error).message,true)}
}

function accessFullName(user:ReportAccessUser){return [user.lastName,user.firstName,user.middleName].filter(Boolean).join(' ')}
function accessUntilLabel(value:string){return new Date(value).toLocaleString('ru-RU',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}
async function reportAccessModal(){
 try{
  const users=await api<ReportAccessUser[]>(`/api/report-access?date=${encodeURIComponent(reportDate)}`),active=users.filter(user=>user.accessUntil),available=users.filter(user=>!user.accessUntil);
  const activeMarkup=active.length?`<section class="access-section"><div class="access-section-head"><b>Доступ открыт</b><span>${active.length}</span></div><div class="access-current-list">${active.map(user=>`<div class="access-current"><span class="access-avatar">${esc((user.firstName?.[0]||'')+(user.lastName?.[0]||''))}</span><span class="access-person"><b>${esc(accessFullName(user))}</b><small>До ${esc(accessUntilLabel(user.accessUntil!))}</small></span><button class="btn btn-danger close-access" type="button" data-id="${user.id}">Закрыть</button></div>`).join('')}</div></section>`:'';
  const availableMarkup=available.length?`<section class="access-section"><div class="access-section-head"><b>Выберите сотрудников</b><button class="access-select-all" type="button">Выбрать всех</button></div><div class="access-check-list">${available.map(user=>`<label class="access-check"><input type="checkbox" value="${user.id}"><span class="access-avatar">${esc((user.firstName?.[0]||'')+(user.lastName?.[0]||''))}</span><span>${esc(accessFullName(user))}</span></label>`).join('')}</div></section>`:`<div class="access-empty">Всем активным сотрудникам доступ уже открыт</div>`;
  showModal('Доступ к отчёту',`<div class="access-intro"><span class="access-date">${new Date(reportDate+'T00:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})}</span><p>Выбранные сотрудники смогут редактировать свой отчёт в течение 24 часов.</p></div>${activeMarkup}${availableMarkup}`,async()=>{
   const userIds=[...document.querySelectorAll<HTMLInputElement>('.access-check input:checked')].map(input=>input.value);if(!userIds.length)return;
   try{await api('/api/report-access',{method:'POST',body:JSON.stringify({date:reportDate,userIds})});closeModal();toast(`Доступ открыт на 24 часа: ${userIds.length}`);await loadReport()}catch(error){toast((error as Error).message,true)}
  },()=>{
   const save=document.querySelector<HTMLButtonElement>('.modal .save')!;save.textContent='Открыть доступ';save.disabled=true;
   const checks=[...document.querySelectorAll<HTMLInputElement>('.access-check input')],sync=()=>save.disabled=!checks.some(input=>input.checked);checks.forEach(input=>input.onchange=sync);
   const selectAll=document.querySelector<HTMLButtonElement>('.access-select-all');if(selectAll)selectAll.onclick=()=>{const allSelected=checks.every(input=>input.checked);checks.forEach(input=>input.checked=!allSelected);selectAll.textContent=allSelected?'Выбрать всех':'Снять выбор';sync()};
   document.querySelectorAll<HTMLButtonElement>('.close-access').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await api('/api/report-access',{method:'DELETE',body:JSON.stringify({date:reportDate,userIds:[button.dataset.id]})});closeModal();toast('Доступ закрыт');await loadReport()}catch(error){button.disabled=false;toast((error as Error).message,true)}});
   if(!available.length)save.hidden=true;
  });
 }catch(error){toast((error as Error).message,true)}
}

async function responsiblesModal(row:Row,cell:HTMLButtonElement){
 try{
  const reportType=isMainReport()?'main_office':'rp',users=await api<ResponsibleUser[]>(`/api/report-responsibles?date=${encodeURIComponent(reportDate)}&reportType=${reportType}&unitId=${encodeURIComponent(row.officeId)}`),assigned=users.filter(user=>user.assigned).length,unitLabel=isMainReport()?'компанию ГО':'РП';
  const list=users.length?`<section class="access-section"><div class="access-section-head"><b>Выберите сотрудников</b><button class="access-select-all" type="button">${assigned===users.length?'Снять выбор':'Выбрать всех'}</button></div><div class="access-check-list">${users.map(user=>`<label class="access-check"><input type="checkbox" value="${user.id}" ${user.assigned?'checked':''}><span class="access-avatar">${esc((user.firstName?.[0]||'')+(user.lastName?.[0]||''))}</span><span>${esc(accessFullName(user))}</span></label>`).join('')}</div></section>`:'<div class="access-empty">Нет активных сотрудников для назначения</div>';
  showModal(`Назначенные · ${row.officeName}`,`<div class="access-intro"><span class="access-date">${displayDate(reportDate)}</span><p>Только выбранные сотрудники смогут заполнять ${unitLabel} «${esc(row.officeName)}» в отчёте за эту дату.</p></div>${list}`,async()=>{
   const userIds=[...document.querySelectorAll<HTMLInputElement>('.access-check input:checked')].map(input=>input.value);
   try{await api('/api/report-responsibles',{method:'PUT',body:JSON.stringify({date:reportDate,reportType,unitId:row.officeId,userIds})});row.responsibleCount=userIds.length;cell.textContent=String(userIds.length);closeModal();toast(`Назначения на ${displayDate(reportDate)} сохранены: ${userIds.length}`)}catch(error){toast((error as Error).message,true)}
  },()=>{
   const checks=[...document.querySelectorAll<HTMLInputElement>('.access-check input')],selectAll=document.querySelector<HTMLButtonElement>('.access-select-all');
   if(selectAll)selectAll.onclick=()=>{const allSelected=checks.length>0&&checks.every(input=>input.checked);checks.forEach(input=>input.checked=!allSelected);selectAll.textContent=allSelected?'Выбрать всех':'Снять выбор'};
  });
 }catch(error){toast((error as Error).message,true)}
}

function hiredSummaryModal(r:Row){const details=r.hiredDetails||[],groups=new Map<string,HiredWorker[]>(),initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'?';details.forEach(x=>{const owner=x.responsible||'Сотрудник не указан';groups.set(owner,[...(groups.get(owner)||[]),x])});const total=details.length||r.hiredWorkers.length,selectedScope=isMainReport()?'по выбранной компании':'по выбранному РП',currentScope=isMainReport()?'по этой компании':'по этому РП',overview=`<div class="summary-count"><div class="summary-count-copy"><b>Принятые сотрудники</b><span>Всего ${selectedScope}</span></div><div class="summary-total"><b>${total}</b><span>чел.</span></div></div>`;let body='';if(groups.size){body=`${overview}<div class="hired-summary">${[...groups].map(([owner,workers])=>`<section class="hired-group"><div class="hired-owner"><span class="owner-avatar">${esc(initials(owner))}</span><div class="owner-meta"><small>Добавил ФИО принятых</small><b>${esc(owner)}</b></div><span class="owner-count"><b>${workers.length}</b><span>чел.</span></span></div><div class="hired-list-title">Кого приняли</div><ol class="hired-names">${workers.map((worker,index)=>`<li><span class="hire-number">${index+1}</span><span class="hire-person"><span class="hire-name">${esc(worker.fullName)}</span>${worker.position?`<small>${esc(worker.position)}</small>`:''}</span></li>`).join('')}</ol></section>`).join('')}</div>`}else{const contributions=(r.contributions?.hiredWorkers||[]).filter(x=>x.value>0);body=contributions.length?`${overview}<div class="hired-summary">${contributions.map(x=>`<section class="hired-group"><div class="hired-owner"><span class="owner-avatar">${esc(initials(x.name))}</span><div class="owner-meta"><small>Добавил ФИО принятых</small><b>${esc(x.name)}</b></div><span class="owner-count"><b>${x.value}</b><span>чел.</span></span></div></section>`).join('')}</div>`:`<div class="modal-empty">Принятых работников ${currentScope} нет</div>`}showInfoModal(`Принятые работники · ${r.officeName}`,body)}
function hiresModal(r:Row,tr:HTMLTableRowElement){let workers:HiredWorker[]=r.hiredWorkers.length?r.hiredWorkers.map(worker=>({...worker})):[{fullName:'',position:''}];const readWorkers=()=>[...document.querySelectorAll<HTMLElement>('.hire-row')].map(row=>({fullName:row.querySelector<HTMLInputElement>('.hire-input')!.value,position:row.querySelector<HTMLInputElement>('.hire-position')!.value}));const body=()=>`<div class="modal-intro"><b>Принятые работники</b><span>ФИО обязательно для записи, должность можно не указывать</span></div><div class="hire-columns" aria-hidden="true"><span></span><span>ФИО сотрудника</span><span>Должность <small>необязательно</small></span><span></span></div><div id="hire-list">${workers.map((worker,i)=>`<div class="hire-row"><span class="hire-index">${i+1}</span><input class="input hire-input" data-i="${i}" value="${esc(worker.fullName)}" placeholder="Фамилия Имя Отчество"><input class="input hire-position" data-i="${i}" value="${esc(worker.position)}" placeholder="Должность"><button class="remove-hire" data-i="${i}" aria-label="Удалить сотрудника">×</button></div>`).join('')}</div><button id="add-hire" class="add-row-button">+ Добавить сотрудника</button>`;showModal('Принятые работники',body(),async()=>{workers=readWorkers().map(worker=>({fullName:worker.fullName.trim(),position:worker.position.trim()})).filter(worker=>worker.fullName);r.hiredWorkers=workers;tr.querySelector<HTMLButtonElement>('.hires')!.textContent=String(workers.length);recalc();await saveNow(r,tr)},wire);function wire(){document.querySelector<HTMLButtonElement>('#add-hire')!.onclick=()=>{workers=readWorkers();workers.push({fullName:'',position:''});document.querySelector('.modal-body')!.innerHTML=body();wire();requestAnimationFrame(()=>{const inputs=document.querySelectorAll<HTMLInputElement>('.hire-input');inputs[inputs.length-1]?.focus()})};document.querySelectorAll<HTMLButtonElement>('.remove-hire').forEach(b=>b.onclick=()=>{workers=readWorkers();workers.splice(Number(b.dataset.i),1);if(!workers.length)workers=[{fullName:'',position:''}];document.querySelector('.modal-body')!.innerHTML=body();wire()})}}
function peopleSummaryModal(r:Row,key:PeopleKey){const config=peopleFields[key],details=r.peopleDetails?.[config.category]||[],groups=new Map<string,string[]>(),initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'?';details.forEach(x=>{const owner=x.responsible||'Сотрудник не указан';groups.set(owner,[...(groups.get(owner)||[]),x.fullName])});const total=details.length||Number(r[key]||0),overview=`<div class="summary-count"><div class="summary-count-copy"><b>${esc(config.itemTitle)}</b><span>Всего по выбранн${isMainReport()?'ой компании':'ому РП'}</span></div><div class="summary-total"><b>${total}</b><span>чел.</span></div></div>`;let body='';if(groups.size){body=`${overview}<div class="hired-summary">${[...groups].map(([owner,names])=>`<section class="hired-group"><div class="hired-owner"><span class="owner-avatar">${esc(initials(owner))}</span><div class="owner-meta"><small>Заполнил список ФИО</small><b>${esc(owner)}</b></div><span class="owner-count"><b>${names.length}</b><span>чел.</span></span></div><div class="hired-list-title">${esc(config.action)}</div><ol class="hired-names">${names.map((name,index)=>`<li><span class="hire-number">${index+1}</span><span class="hire-name">${esc(name)}</span></li>`).join('')}</ol></section>`).join('')}</div>`}else{const contributions=(r.contributions?.[key]||[]).filter(x=>x.value>0);body=contributions.length?`${overview}<div class="hired-summary">${contributions.map(x=>`<section class="hired-group"><div class="hired-owner"><span class="owner-avatar">${esc(initials(x.name))}</span><div class="owner-meta"><small>Данные без списка ФИО</small><b>${esc(x.name)}</b></div><span class="owner-count"><b>${x.value}</b><span>чел.</span></span></div></section>`).join('')}</div>`:`<div class="modal-empty">В этом списке пока никого нет</div>`}showInfoModal(`${config.itemTitle} · ${r.officeName}`,body)}
function plannedDismissalsModal(r:Row){const people=r.plannedDismissals||[],overview=`<div class="summary-count"><div class="summary-count-copy"><b>Планируемый резерв</b><span>Сотрудники с планируемым увольнением · данные Debtster только для просмотра</span></div><div class="summary-total"><b>${Number(r.plannedDismissalsCount||0)}</b><span>чел.</span></div></div>`,list=people.length?`<div class="hired-summary"><section class="hired-group"><div class="hired-list-title">Список сотрудников</div><ol class="hired-names">${people.map((person,index)=>{const name=[person.last_name,person.first_name,person.middle_name].filter(Boolean).join(' ');return `<li><span class="hire-number">${index+1}</span><span class="hire-name">${esc(name)}</span></li>`}).join('')}</ol></section></div>`:`<div class="modal-empty">Debtster не вернул список сотрудников</div>`;showInfoModal(`Планируемый резерв · ${r.officeName}`,overview+list)}
function peopleModal(r:Row,tr:HTMLTableRowElement,key:PeopleKey){const config=peopleFields[key];r.people||={};let names=r.people[config.category]?.length?[...r.people[config.category]!]:[''];const body=()=>`<div class="modal-intro"><b>${esc(config.itemTitle)}</b><span>Укажите полное ФИО каждого человека</span></div><div id="hire-list">${names.map((name,index)=>`<div class="hire-row people-row"><span class="hire-index">${index+1}</span><input class="input hire-input" data-i="${index}" value="${esc(name)}" placeholder="Фамилия Имя Отчество"><button class="remove-hire" data-i="${index}" aria-label="Удалить">×</button></div>`).join('')}</div><button id="add-hire" class="add-row-button">+ Добавить</button>`;showModal(config.title,body(),async()=>{names=[...document.querySelectorAll<HTMLInputElement>('.hire-input')].map(input=>input.value.trim()).filter(Boolean);r.people[config.category]=names;r[key]=names.length;tr.querySelector<HTMLButtonElement>(`.people-list[data-people-key="${key}"]`)!.textContent=String(names.length);updateEfficiencyCells(r,tr);recalc();await saveNow(r,tr)},wire);function wire(){document.querySelector<HTMLButtonElement>('#add-hire')!.onclick=()=>{names=[...document.querySelectorAll<HTMLInputElement>('.hire-input')].map(input=>input.value);names.push('');document.querySelector('.modal-body')!.innerHTML=body();wire();requestAnimationFrame(()=>{const inputs=document.querySelectorAll<HTMLInputElement>('.hire-input');inputs[inputs.length-1]?.focus()})};document.querySelectorAll<HTMLButtonElement>('.remove-hire').forEach(button=>button.onclick=()=>{names=[...document.querySelectorAll<HTMLInputElement>('.hire-input')].map(input=>input.value);names.splice(Number(button.dataset.i),1);if(!names.length)names=[''];document.querySelector('.modal-body')!.innerHTML=body();wire()})}}
async function saveNow(r:Row,tr:HTMLTableRowElement){setSaveState('saving');try{const x=await api<{efficiency:number;invitationEfficiency:number;hiringEfficiency:number}>(`${isMainReport()?'/api/main-office/report/rows':'/api/report/rows'}/${r.id}`,{method:'PUT',body:JSON.stringify(rowPayload(r))});r.efficiency=x.efficiency;r.invitationEfficiency=x.invitationEfficiency;r.hiringEfficiency=x.hiringEfficiency;updateEfficiencyCells(r,tr);dirtyRows.delete(r.id);setSaveState(dirtyRows.size?'saving':'saved');closeModal();toast('Сохранено')}catch(e){setSaveState('failed');toast((e as Error).message,true)}}

function showModal(name:string,body:string,onSave:()=>void|Promise<void>,after?:()=>void){closeModal();modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true" aria-label="${esc(name)}"><div class="modal-head"><h2>${esc(name)}</h2><button class="close" aria-label="Закрыть">×</button></div><div class="modal-body">${body}</div><div class="modal-foot"><span class="modal-hint">Esc — закрыть · Ctrl+Enter — сохранить</span><button class="btn btn-outline cancel">Отмена</button><button class="btn btn-primary save">Сохранить</button></div></div></div>`;modalRoot.querySelectorAll<HTMLElement>('.close,.cancel').forEach(x=>x.onclick=closeModal);const save=modalRoot.querySelector<HTMLButtonElement>('.save')!;save.onclick=()=>onSave();modalKeyHandler=e=>{if(e.key==='Escape'){e.preventDefault();closeModal()}else if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();save.click()}};document.addEventListener('keydown',modalKeyHandler);after?.();requestAnimationFrame(()=>modalRoot.querySelector<HTMLElement>('input,button,select')?.focus())}
function showInfoModal(name:string,body:string){closeModal();modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal summary-modal" role="dialog" aria-modal="true" aria-label="${esc(name)}"><div class="modal-head"><h2>${esc(name)}</h2><button class="close" aria-label="Закрыть">×</button></div><div class="modal-body">${body}</div><div class="modal-foot"><button class="btn btn-primary close-info">Закрыть</button></div></div></div>`;modalRoot.querySelectorAll<HTMLElement>('.close,.close-info').forEach(x=>x.onclick=closeModal);modalKeyHandler=e=>{if(e.key==='Escape'){e.preventDefault();closeModal()}};document.addEventListener('keydown',modalKeyHandler)}
function closeModal(){if(modalKeyHandler){document.removeEventListener('keydown',modalKeyHandler);modalKeyHandler=null}modalRoot.innerHTML=''}
function download(url:string){location.href=url}

async function historyPage(){setHeader('История отчётов','Архив и выгрузка отчётов за период');const from=new Date(Date.now()-30*86400000).toISOString().slice(0,10),to=today();content.innerHTML=`<div class="toolbar"><div class="field"><label>С даты</label><input id="from" class="input" type="date" value="${from}"></div><div class="field"><label>По дату</label><input id="to" class="input" type="date" value="${to}"></div><button id="find" class="btn btn-primary">Показать</button><div class="spacer"></div><button id="period-export" class="btn btn-outline">Выгрузить период</button></div><div class="card"><div id="history-list"></div></div>`;const load=async()=>{const f=(document.querySelector('#from') as HTMLInputElement).value,t=(document.querySelector('#to') as HTMLInputElement).value,rows=await api<any[]>(`/api/reports/history?from=${f}&to=${t}`);document.querySelector('#history-list')!.innerHTML=rows.length?`<table class="data-table"><thead><tr><th>Дата</th><th>Статус</th><th>Порог</th><th>Приглашено</th><th>Стажёры</th><th>Принято</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.date}</td><td><span class="status-pill ${x.status}">${x.status==='completed'?'Завершён':'Черновик'}</span></td><td>${x.threshold}</td><td>${x.invited}</td><td>${x.interns}</td><td>${x.hires}</td><td><button class="btn btn-outline open-report" data-date="${x.date}">Открыть</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">За выбранный период отчётов нет</div>';document.querySelectorAll<HTMLButtonElement>('.open-report').forEach(b=>b.onclick=()=>{reportDate=b.dataset.date!;currentPage='report';drawNav();route()})};document.querySelector<HTMLButtonElement>('#find')!.onclick=load;document.querySelector<HTMLButtonElement>('#period-export')!.onclick=()=>download(`/api/reports/export?from=${(document.querySelector('#from') as HTMLInputElement).value}&to=${(document.querySelector('#to') as HTMLInputElement).value}`);await load()}

async function employeesPage(){setHeader('Сотрудники','Справочник сотрудников и массовый импорт');const rows=await api<Employee[]>('/api/employees');content.innerHTML=`<div class="card"><div class="card-head"><h2>Сотрудники <span class="muted">${rows.length}</span></h2><div><button id="template" class="btn btn-outline">Скачать шаблон</button> <button id="import" class="btn btn-outline">Импорт XLSX</button> <button id="new-employee" class="btn btn-primary">+ Добавить</button></div></div><table class="data-table"><thead><tr><th>Фамилия</th><th>Имя</th><th>Отчество</th><th>Статус</th><th></th></tr></thead><tbody>${rows.map(e=>`<tr><td>${esc(e.lastName)}</td><td>${esc(e.firstName)}</td><td>${esc(e.middleName)}</td><td>${e.active?'Активен':'Архив'}</td><td><button class="btn btn-outline edit-employee" data-id="${e.id}">Изменить</button></td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">Добавьте первого сотрудника</div>'}</div>`;document.querySelector<HTMLButtonElement>('#template')!.onclick=()=>download('/api/employees/template');document.querySelector<HTMLButtonElement>('#import')!.onclick=importModal;document.querySelector<HTMLButtonElement>('#new-employee')!.onclick=()=>employeeModal();document.querySelectorAll<HTMLButtonElement>('.edit-employee').forEach(b=>b.onclick=()=>employeeModal(rows.find(x=>x.id===b.dataset.id)))}
function employeeModal(e?:Employee){showModal(e?'Редактировать сотрудника':'Новый сотрудник',`<div class="grid-form"><div class="field"><label>Фамилия</label><input id="last" class="input" value="${esc(e?.lastName||'')}"></div><div class="field"><label>Имя</label><input id="first" class="input" value="${esc(e?.firstName||'')}"></div><div class="field"><label>Отчество</label><input id="middle" class="input" value="${esc(e?.middleName||'')}"></div></div>`,async()=>{const x={lastName:(document.querySelector('#last') as HTMLInputElement).value,firstName:(document.querySelector('#first') as HTMLInputElement).value,middleName:(document.querySelector('#middle') as HTMLInputElement).value,active:e?.active??true};await api(e?`/api/employees/${e.id}`:'/api/employees',{method:e?'PUT':'POST',body:JSON.stringify(x)});closeModal();toast('Сотрудник сохранён');employeesPage()})}
function importModal(){showModal('Импорт сотрудников',`<p class="muted">XLSX должен содержать строго три колонки: <b>Имя, Фамилия, Отчество</b>.</p><input id="import-file" class="input" type="file" accept=".xlsx"><div id="import-progress" style="display:none;margin-top:18px"><div class="progress"><span style="width:0"></span></div><p id="progress-text"></p><div class="error-list"></div></div>`,async()=>{const file=(document.querySelector('#import-file') as HTMLInputElement).files?.[0];if(!file){toast('Выберите файл',true);return}const fd=new FormData();fd.append('file',file);const x=await api<{id:string}>('/api/imports/employees',{method:'POST',body:fd});const box=document.querySelector<HTMLElement>('#import-progress')!;box.style.display='block';const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/imports/${x.id}`);ws.onmessage=ev=>{const p=JSON.parse(ev.data),percent=p.total?Math.round(p.processed*100/p.total):0;(box.querySelector('.progress span') as HTMLElement).style.width=percent+'%';box.querySelector('#progress-text')!.textContent=`Обработано ${p.processed} из ${p.total}, импортировано ${p.imported}`;box.querySelector('.error-list')!.innerHTML=(p.errors||[]).map((e:any)=>`Строка ${e.row}: ${esc(e.message)}`).join('<br>');if(p.status==='completed'||p.status==='failed'){ws.close();toast(p.status==='completed'?'Импорт завершён':'Ошибка импорта',p.status==='failed')}};document.querySelector<HTMLButtonElement>('.modal .save')!.disabled=true})}

async function usersPage(){
 const rows=await api<User[]>('/api/users'),name=(u:User)=>[u.lastName,u.firstName,u.middleName].filter(Boolean).join(' ');
 setHeader('Пользователи','Сотрудники и роли');
 content.innerHTML=`<div class="card admin-card"><div class="card-head"><div class="list-heading"><h2>Пользователи</h2><span>${rows.length} активных учётных записей</span></div><div class="page-actions"><label class="table-search">${icons.search}<input id="user-search" type="search" placeholder="Найти по ФИО или логину" aria-label="Поиск пользователей"></label><button id="new-user" class="btn btn-primary">+ Добавить сотрудника</button></div></div><div class="table-scroll"><table class="data-table"><thead><tr><th>ФИО</th><th>Логин</th><th>Роль</th><th>Планы РП</th><th>Планы ГО</th><th class="actions-col">Действия</th></tr></thead><tbody>${rows.map(u=>`<tr data-search="${esc((name(u)+' '+u.username).toLowerCase())}"><td class="primary-cell">${esc(name(u))}</td><td><span class="login-value">${esc(u.username)}</span></td><td><span class="role-badge ${u.role}">${u.role==='admin'?'Администратор':'Сотрудник'}</span></td><td>${u.role==='employee'?`<span class="plan-summary">Пригл. <b>${u.invitationPlan}</b> · Прин. <b>${u.plan}</b></span>`:'—'}</td><td>${u.role==='employee'?`<span class="plan-summary">Пригл. <b>${u.mainOfficeInvitationPlan}</b> · Прин. <b>${u.mainOfficePlan}</b></span>`:'—'}</td><td class="row-actions">${u.role==='employee'?`<button class="btn btn-outline edit-plans" data-id="${u.id}">Планы</button>`:''}<button class="btn btn-outline edit-user" data-id="${u.id}">Изменить</button><button class="btn btn-danger delete-user" data-id="${u.id}">Удалить</button></td></tr>`).join('')}</tbody></table></div>${rows.length?'':'<div class="empty">Добавьте первого сотрудника</div>'}<div class="filter-empty" hidden>По вашему запросу ничего не найдено</div></div>`;
 const search=document.querySelector<HTMLInputElement>('#user-search')!;search.oninput=()=>filterRows(search.value);
 document.querySelector<HTMLButtonElement>('#new-user')!.onclick=()=>userModal();
 document.querySelectorAll<HTMLButtonElement>('.edit-user').forEach(b=>b.onclick=()=>userModal(rows.find(x=>x.id===b.dataset.id)));
 document.querySelectorAll<HTMLButtonElement>('.edit-plans').forEach(b=>b.onclick=()=>candidatePlansModal(rows.find(x=>x.id===b.dataset.id)!));
 document.querySelectorAll<HTMLButtonElement>('.delete-user').forEach(b=>b.onclick=async()=>{const u=rows.find(x=>x.id===b.dataset.id)!;if(!confirm(`Удалить учётную запись ${u.username}? Восстановить сотрудника будет нельзя.`))return;try{await api(`/api/users/${u.id}`,{method:'DELETE'});toast('Сотрудник удалён');await usersPage()}catch(e){toast((e as Error).message,true)}})
}
async function exportPage(){const own=!manager();setHeader('Выгрузка',own?'Мои показатели за выбранный период':'Сводные показатели за выбранный период');const from=today(),to=today();content.innerHTML=`<div class="card export-panel"><div class="card-head"><h2>Выгрузка XLSX за период</h2></div><div class="panel-body"><div class="export-form"><div class="field"><label>Тип отчёта</label><select id="export-report-type"><option value="rp">РП</option><option value="main_office">ГО</option><option value="all">Все</option></select></div><div class="field"><label>Дата начала</label><input id="export-from" class="input" type="date" value="${from}"></div><div class="field"><label>Дата окончания</label><input id="export-to" class="input" type="date" value="${to}"></div></div><div class="export-note"><b>${own?'Только мои отчёты':'Сводный отчёт и сотрудники'}</b><span>${own?'В файл попадут только данные из отчётов, заполненных под вашей учётной записью.':'Каждый выбранный тип отчёта получает отдельный лист: сначала общая таблица, затем персональные таблицы сотрудников.'}</span></div><div class="export-note"><b>Принятые сотрудники и списки ФИО</b><span>Для РП и ГО создаются отдельные листы с принятыми сотрудниками, их должностями и детализацией кадровых показателей.</span></div></div><div class="panel-actions"><button id="download-period" class="btn btn-primary with-icon">${icons.download}<span>Скачать XLSX</span></button></div></div>`;document.querySelector<HTMLButtonElement>('#download-period')!.onclick=()=>{const start=(document.querySelector('#export-from') as HTMLInputElement).value,end=(document.querySelector('#export-to') as HTMLInputElement).value,reportType=(document.querySelector('#export-report-type') as HTMLSelectElement).value;if(!start||!end||start>end){toast('Укажите корректный период',true);return}download(`/api/reports/export?from=${encodeURIComponent(start)}&to=${encodeURIComponent(end)}&reportType=${encodeURIComponent(reportType)}`)}}
function userModal(u?:User){
 const canChooseRole=currentUser?.role==='superadmin',planSection=!u?`<section class="form-section candidate-plan-option" id="candidate-plan-option"><label class="plan-toggle"><input id="add-candidate-plans" type="checkbox"><span><b>Добавить планы кандидатов</b><small>Указать планы по приглашённым и принятым кандидатам для РП и ГО</small></span></label></section><div class="candidate-plans-panel" id="candidate-plans-panel" hidden>${candidatePlansFields()}</div>`:'';
 showModal(u?'Изменить пользователя':'Новый пользователь',`<div class="user-form"><section class="form-section"><div class="form-section-head"><b>Данные сотрудника</b><span>ФИО отображается в отчётах и подсказках таблицы</span></div><div class="person-grid"><div class="field"><label>Фамилия</label><input id="user-last" class="input" placeholder="Например, Иванов" value="${esc(u?.lastName||'')}"></div><div class="field"><label>Имя</label><input id="user-first" class="input" placeholder="Иван" value="${esc(u?.firstName||'')}"></div><div class="field"><label>Отчество</label><input id="user-middle" class="input" placeholder="Иванович" value="${esc(u?.middleName||'')}"></div></div></section><section class="form-section"><div class="form-section-head"><b>Доступ к системе</b><span>Логин должен быть уникальным, пароль — не короче 8 символов</span></div><div class="access-grid"><div class="field"><label>Логин</label><input id="user-login" class="input" autocomplete="off" value="${esc(u?.username||'')}"></div><div class="field"><label>${u?'Новый пароль':'Пароль'}</label><input id="user-password" class="input" type="password" autocomplete="new-password" placeholder="${u?'Оставьте пустым, чтобы не менять':'Минимум 8 символов'}"></div><div class="field"><label>Роль</label><select id="user-role" ${canChooseRole?'':'disabled'}><option value="employee">Сотрудник</option>${canChooseRole?'<option value="admin">Администратор</option>':''}</select></div></div></section>${planSection}</div>`,async()=>{const role=(document.querySelector('#user-role') as HTMLSelectElement).value,addPlans=!u&&role==='employee'&&(document.querySelector<HTMLInputElement>('#add-candidate-plans')?.checked||false),plans=addPlans?readCandidatePlans():null;if(plans&&!validCandidatePlans(plans)){toast('Заполните дату и укажите целые неотрицательные планы',true);return}const payload={lastName:(document.querySelector('#user-last') as HTMLInputElement).value,firstName:(document.querySelector('#user-first') as HTMLInputElement).value,middleName:(document.querySelector('#user-middle') as HTMLInputElement).value,username:(document.querySelector('#user-login') as HTMLInputElement).value,password:(document.querySelector('#user-password') as HTMLInputElement).value,role,active:true,plan:plans?.rpHired||0,planFrom:plans?.effectiveFrom||'',mainOfficePlan:plans?.mainOfficeHired||0,mainOfficePlanFrom:plans?.effectiveFrom||'',invitationPlan:plans?.rpInvited||0,mainOfficeInvitationPlan:plans?.mainOfficeInvited||0};try{await api(u?`/api/users/${u.id}`:'/api/users',{method:u?'PUT':'POST',body:JSON.stringify(payload)});closeModal();toast('Пользователь сохранён');adminUsers=[];await usersPage()}catch(e){toast((e as Error).message,true)}})
 if(!u){const toggle=document.querySelector<HTMLInputElement>('#add-candidate-plans')!,panel=document.querySelector<HTMLElement>('#candidate-plans-panel')!,option=document.querySelector<HTMLElement>('#candidate-plan-option')!,role=document.querySelector<HTMLSelectElement>('#user-role')!;toggle.onchange=()=>{panel.hidden=!toggle.checked};const syncRole=()=>{const employee=role.value==='employee';option.hidden=!employee;panel.hidden=!employee||!toggle.checked};role.addEventListener('change',syncRole);syncRole()}
}
function candidatePlansFields(u?:User){return `<section class="form-section candidate-plans-section"><div class="form-section-head candidate-plans-head"><div class="candidate-plans-copy"><b>Планы кандидатов</b><span>Отдельные значения для отчётов РП и ГО</span></div><div class="field plan-effective-date"><label>Действуют с</label><input id="candidate-plans-from" class="input" type="date" value="${today()}"></div></div><div class="candidate-plan-matrix"><div class="matrix-head"></div><div class="matrix-head">РП</div><div class="matrix-head">ГО</div><label><span>Приглашённые кандидаты</span></label><input id="plan-rp-invited" class="input" type="number" min="0" step="1" inputmode="numeric" value="${u?.invitationPlan||0}"><input id="plan-main-invited" class="input" type="number" min="0" step="1" inputmode="numeric" value="${u?.mainOfficeInvitationPlan||0}"><label><span>Принятые кандидаты</span></label><input id="plan-rp-hired" class="input" type="number" min="0" step="1" inputmode="numeric" value="${u?.plan||0}"><input id="plan-main-hired" class="input" type="number" min="0" step="1" inputmode="numeric" value="${u?.mainOfficePlan||0}"></div></section>`}
function readCandidatePlans(){return{effectiveFrom:(document.querySelector('#candidate-plans-from') as HTMLInputElement).value,rpInvited:Number((document.querySelector('#plan-rp-invited') as HTMLInputElement).value),rpHired:Number((document.querySelector('#plan-rp-hired') as HTMLInputElement).value),mainOfficeInvited:Number((document.querySelector('#plan-main-invited') as HTMLInputElement).value),mainOfficeHired:Number((document.querySelector('#plan-main-hired') as HTMLInputElement).value)}}
function validCandidatePlans(plans:ReturnType<typeof readCandidatePlans>){return !!plans.effectiveFrom&&[plans.rpInvited,plans.rpHired,plans.mainOfficeInvited,plans.mainOfficeHired].every(value=>Number.isInteger(value)&&value>=0)}
function candidatePlansModal(u:User){showModal(`Планы · ${[u.lastName,u.firstName].filter(Boolean).join(' ')}`,candidatePlansFields(u),async()=>{const plans=readCandidatePlans();if(!validCandidatePlans(plans)){toast('Заполните дату и укажите целые неотрицательные планы',true);return}await api(`/api/users/${u.id}/candidate-plans`,{method:'PUT',body:JSON.stringify(plans)});closeModal();toast('Планы сотрудника сохранены');await usersPage()})}
async function officesPage(){setHeader('РП','Отдельный справочник подразделений');const rows=await api<any[]>('/api/offices');content.innerHTML=`<div class="card admin-card"><div class="card-head"><div class="list-heading"><h2>РП</h2><span>${rows.filter(o=>o.active).length} активных · ${rows.filter(o=>!o.active).length} архивных</span></div><div class="page-actions"><select id="office-status" aria-label="Статус РП"><option value="active">Активные РП</option><option value="archived">Архивные РП</option><option value="all">Все РП</option></select><label class="table-search">${icons.search}<input id="office-search" type="search" placeholder="Найти РП" aria-label="Поиск РП"></label><button id="new-office" class="btn btn-primary">+ Добавить РП</button></div></div><div class="table-scroll"><table class="data-table office-table"><thead><tr><th class="order-col">Порядок</th><th>Название РП</th><th>Статус</th><th class="actions-col">Действия</th></tr></thead><tbody>${rows.map((o,i)=>`<tr data-id="${o.id}" data-active="${o.active?'true':'false'}" data-search="${esc(String(o.name).toLowerCase())}"><td><span class="drag-handle" draggable="true" aria-label="Перетащить РП"><i></i><span class="sort-value">${i+1}</span></span></td><td class="primary-cell">${esc(o.name)}</td><td><span class="state-badge ${o.active?'active':'inactive'}"><i></i>${o.active?'Активно':'Архив'}</span></td><td class="row-actions"><button class="btn btn-outline edit-office" data-id="${o.id}">${o.active?'Изменить':'Просмотреть / восстановить'}</button></td></tr>`).join('')}</tbody></table></div><div class="filter-empty" hidden>По выбранному фильтру ничего не найдено</div></div>`;const search=document.querySelector<HTMLInputElement>('#office-search')!,status=document.querySelector<HTMLSelectElement>('#office-status')!,apply=()=>{const query=search.value.trim().toLowerCase();let shown=0;content.querySelectorAll<HTMLTableRowElement>('.office-table tbody tr').forEach(row=>{const matchesStatus=status.value==='all'||(status.value==='active'&&row.dataset.active==='true')||(status.value==='archived'&&row.dataset.active==='false'),visible=matchesStatus&&(!query||(row.dataset.search||'').includes(query));row.hidden=!visible;if(visible)shown++});content.querySelector<HTMLElement>('.filter-empty')!.hidden=shown>0};search.oninput=apply;status.onchange=apply;apply();document.querySelector<HTMLButtonElement>('#new-office')!.onclick=()=>officeModal();document.querySelectorAll<HTMLButtonElement>('.edit-office').forEach(b=>b.onclick=()=>officeModal(rows.find(x=>x.id===b.dataset.id)));wireOfficeSorting()}
function wireOfficeSorting(){const tbody=content.querySelector<HTMLTableSectionElement>('.office-table tbody');if(!tbody)return;let dragged:HTMLTableRowElement|null=null;tbody.querySelectorAll<HTMLElement>('.drag-handle').forEach(handle=>{handle.ondragstart=e=>{dragged=handle.closest('tr');dragged?.classList.add('dragging');if(e.dataTransfer){e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragged?.dataset.id||'')}};handle.ondragend=()=>{dragged?.classList.remove('dragging');dragged=null;tbody.querySelectorAll('tr').forEach(row=>row.classList.remove('drag-over'))}});tbody.ondragover=e=>{if(!dragged)return;e.preventDefault();const target=(e.target as HTMLElement).closest<HTMLTableRowElement>('tr');if(!target||target===dragged)return;tbody.querySelectorAll('tr').forEach(row=>row.classList.remove('drag-over'));target.classList.add('drag-over');const after=e.clientY>target.getBoundingClientRect().top+target.offsetHeight/2;tbody.insertBefore(dragged,after?target.nextSibling:target)};tbody.ondrop=async e=>{if(!dragged)return;e.preventDefault();tbody.querySelectorAll('tr').forEach(row=>row.classList.remove('drag-over'));const ordered=[...tbody.querySelectorAll<HTMLTableRowElement>('tr')];ordered.forEach((row,i)=>{const number=row.querySelector<HTMLElement>('.sort-value');if(number)number.textContent=String(i+1)});try{await api('/api/offices/order',{method:'PUT',body:JSON.stringify({ids:ordered.map(row=>row.dataset.id)})});toast('Порядок РП сохранён')}catch(error){toast((error as Error).message,true);officesPage()}}}
function officeModal(o?:any){showModal(o?'Изменить РП':'Новое РП',`<div class="office-form"><div class="form-section-head"><b>Параметры РП</b><span>Архивное РП не добавляется в новые отчёты, но сохраняется в старых.</span></div><div class="field"><label>Название РП</label><input id="office-name" class="input" placeholder="Введите полное название" value="${esc(o?.name||'')}"></div>${o?`<label class="active-switch"><input id="office-active" type="checkbox" ${o.active?'checked':''}><span><b>РП активно</b><small>Отключите, чтобы перенести РП в архив</small></span></label>`:''}</div>`,async()=>{const x={name:(document.querySelector('#office-name') as HTMLInputElement).value,active:o?(document.querySelector('#office-active') as HTMLInputElement).checked:true};await api(o?`/api/offices/${o.id}`:'/api/offices',{method:o?'PUT':'POST',body:JSON.stringify(x)});closeModal();toast(x.active?'РП сохранено':'РП перенесено в архив');officesPage()})}
async function mainOfficesPage(){setHeader('Компании главного офиса','Отдельный справочник компаний');const rows=await api<any[]>('/api/main-offices');content.innerHTML=`<div class="card admin-card"><div class="card-head"><div class="list-heading"><h2>Компании</h2><span>${rows.filter(o=>o.active).length} активных · ${rows.filter(o=>!o.active).length} архивных</span></div><div class="page-actions"><select id="office-status" aria-label="Статус компании"><option value="active">Активные компании</option><option value="archived">Архивные компании</option><option value="all">Все компании</option></select><label class="table-search">${icons.search}<input id="office-search" type="search" placeholder="Найти компанию" aria-label="Поиск компаний"></label><button id="new-main-office" class="btn btn-primary">+ Добавить компанию</button></div></div><div class="table-scroll"><table class="data-table office-table"><thead><tr><th class="order-col">Порядок</th><th>Название компании</th><th>Статус</th><th class="actions-col">Действия</th></tr></thead><tbody>${rows.map((o,i)=>`<tr data-id="${o.id}" data-active="${o.active?'true':'false'}" data-search="${esc(String(o.name).toLowerCase())}"><td><span class="drag-handle" draggable="true" aria-label="Перетащить компанию"><i></i><span class="sort-value">${i+1}</span></span></td><td class="primary-cell">${esc(o.name)}</td><td><span class="state-badge ${o.active?'active':'inactive'}"><i></i>${o.active?'Активна':'Архив'}</span></td><td class="row-actions"><button class="btn btn-outline edit-main-office" data-id="${o.id}">${o.active?'Изменить':'Просмотреть / восстановить'}</button></td></tr>`).join('')}</tbody></table></div><div class="filter-empty" hidden>По выбранному фильтру ничего не найдено</div></div>`;const search=document.querySelector<HTMLInputElement>('#office-search')!,status=document.querySelector<HTMLSelectElement>('#office-status')!,apply=()=>{const query=search.value.trim().toLowerCase();let shown=0;content.querySelectorAll<HTMLTableRowElement>('.office-table tbody tr').forEach(row=>{const matchesStatus=status.value==='all'||(status.value==='active'&&row.dataset.active==='true')||(status.value==='archived'&&row.dataset.active==='false'),visible=matchesStatus&&(!query||(row.dataset.search||'').includes(query));row.hidden=!visible;if(visible)shown++});content.querySelector<HTMLElement>('.filter-empty')!.hidden=shown>0};search.oninput=apply;status.onchange=apply;apply();document.querySelector<HTMLButtonElement>('#new-main-office')!.onclick=()=>mainOfficeModal();document.querySelectorAll<HTMLButtonElement>('.edit-main-office').forEach(button=>button.onclick=()=>mainOfficeModal(rows.find(x=>x.id===button.dataset.id)));wireMainOfficeSorting()}
function wireMainOfficeSorting(){const tbody=content.querySelector<HTMLTableSectionElement>('.office-table tbody');if(!tbody)return;let dragged:HTMLTableRowElement|null=null;tbody.querySelectorAll<HTMLElement>('.drag-handle').forEach(handle=>{handle.ondragstart=e=>{dragged=handle.closest('tr');dragged?.classList.add('dragging');if(e.dataTransfer){e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragged?.dataset.id||'')}};handle.ondragend=()=>{dragged?.classList.remove('dragging');dragged=null;tbody.querySelectorAll('tr').forEach(row=>row.classList.remove('drag-over'))}});tbody.ondragover=e=>{if(!dragged)return;e.preventDefault();const target=(e.target as HTMLElement).closest<HTMLTableRowElement>('tr');if(!target||target===dragged)return;tbody.querySelectorAll('tr').forEach(row=>row.classList.remove('drag-over'));target.classList.add('drag-over');const after=e.clientY>target.getBoundingClientRect().top+target.offsetHeight/2;tbody.insertBefore(dragged,after?target.nextSibling:target)};tbody.ondrop=async e=>{if(!dragged)return;e.preventDefault();const ordered=[...tbody.querySelectorAll<HTMLTableRowElement>('tr')];ordered.forEach((row,i)=>{const number=row.querySelector<HTMLElement>('.sort-value');if(number)number.textContent=String(i+1)});try{await api('/api/main-offices/order',{method:'PUT',body:JSON.stringify({ids:ordered.map(row=>row.dataset.id)})});toast('Порядок компаний сохранён')}catch(error){toast((error as Error).message,true);mainOfficesPage()}}}
function mainOfficeModal(o?:any){showModal(o?'Изменить компанию':'Новая компания',`<div class="office-form"><div class="form-section-head"><b>Параметры компании</b><span>Архивная компания не добавляется в новые отчёты, но сохраняется в старых.</span></div><div class="field"><label>Название компании</label><input id="main-office-name" class="input" placeholder="Введите название компании" value="${esc(o?.name||'')}"></div>${o?`<label class="active-switch"><input id="main-office-active" type="checkbox" ${o.active?'checked':''}><span><b>Компания активна</b><small>Отключите, чтобы перенести компанию в архив</small></span></label>`:''}</div>`,async()=>{const x={name:(document.querySelector('#main-office-name') as HTMLInputElement).value,active:o?(document.querySelector('#main-office-active') as HTMLInputElement).checked:true};await api(o?`/api/main-offices/${o.id}`:'/api/main-offices',{method:o?'PUT':'POST',body:JSON.stringify(x)});closeModal();toast(x.active?'Компания сохранена':'Компания перенесена в архив');mainOfficesPage()})}
async function importsPage(){setHeader('Импорты','История фоновых операций');const rows=await api<any[]>('/api/imports');content.innerHTML=`<div class="card"><table class="data-table"><thead><tr><th>Дата</th><th>Файл</th><th>Статус</th><th>Прогресс</th><th>Импортировано</th><th>Ошибки</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString('ru')}</td><td>${esc(x.fileName)}</td><td>${statusRu(x.status)}</td><td>${x.processedRows} / ${x.totalRows}</td><td>${x.importedRows}</td><td>${(x.errors||[]).length}</td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">Импортов пока нет</div>'}</div>`}
function statusRu(s:string){return({queued:'В очереди',processing:'Обработка',completed:'Завершён',failed:'Ошибка'} as any)[s]||s}
function filterRows(query:string){const value=query.trim().toLowerCase();let shown=0;content.querySelectorAll<HTMLTableRowElement>('.data-table tbody tr').forEach(row=>{const visible=!value||(row.dataset.search||'').includes(value);row.hidden=!visible;if(visible)shown++});const empty=content.querySelector<HTMLElement>('.filter-empty');if(empty)empty.hidden=shown>0}
async function auditPage(){setHeader('Журнал действий','Последние изменения в системе');const rows=await api<any[]>('/api/audit');content.innerHTML=`<div class="card"><table class="data-table"><thead><tr><th>Дата и время</th><th>Пользователь</th><th>Действие</th><th>Объект</th><th>Идентификатор</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString('ru')}</td><td>${esc(x.actor)}</td><td>${esc(x.action)}</td><td>${esc(x.entityType)}</td><td class="muted">${esc(x.entityId)}</td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">Событий пока нет</div>'}</div>`}

document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.body.classList.remove('table-fullscreen')});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')scheduleDebtsterRefresh();else stopDebtsterRefresh()});
window.addEventListener('resize',()=>{closeDatePicker();if((currentPage==='report'||currentPage==='main-report')&&!hasCustomColumnWidths())applyColumnWidths()});
window.addEventListener('beforeunload',e=>{if(dirtyRows.size){e.preventDefault();e.returnValue='Есть несохранённые изменения'}});
document.querySelector<HTMLButtonElement>('#logout')!.onclick=async()=>{await api('/api/auth/logout',{method:'POST',body:'{}'});stopDebtsterRefresh();currentUser=null;showLogin()};
function configureUser(){if(!currentUser)return;const exportNav=['exports',icons.download,'Выгрузка'];pages=manager()?[...reportPage,exportNav,['users',icons.employees,'Пользователи'],['main-offices',icons.mainOffice,'ГО']]:[...reportPage,exportNav];const display=[currentUser.lastName,currentUser.firstName,currentUser.middleName].filter(Boolean).join(' ')||currentUser.username;document.querySelector('#profile-name')!.textContent=display;document.querySelector('#profile-role')!.textContent=currentUser.role==='superadmin'?'Суперадминистратор':currentUser.role==='admin'?'Администратор':'Сотрудник';document.querySelector('#profile-avatar')!.textContent=((currentUser.firstName?.[0]||'')+(currentUser.lastName?.[0]||currentUser.username[0]||'')).toUpperCase();reportDate=businessToday();currentPage='report';selectedEmployee='';adminUsers=[];drawNav();route()}
function showLogin(message=''){document.body.classList.add('logged-out');modalRoot.innerHTML=`<div class="login-screen"><form class="login-card" id="login-form"><div class="login-brand"><span class="brand-mark">HR</span><div><strong>HR Daily</strong></div></div><div class="login-copy"><h1>Вход в систему</h1><p>Введите логин и пароль учётной записи</p></div><div class="field"><label>Логин</label><input id="login-name" class="input" autocomplete="username" autofocus></div><div class="field"><label>Пароль</label><input id="login-password" class="input" type="password" autocomplete="current-password"></div><div id="login-error" class="login-error">${esc(message)}</div><button class="btn btn-primary login-submit" type="submit">Войти</button></form></div>`;document.querySelector<HTMLFormElement>('#login-form')!.onsubmit=async e=>{e.preventDefault();const button=document.querySelector<HTMLButtonElement>('.login-submit')!;button.disabled=true;button.textContent='Вход...';try{currentUser=await api<User>('/api/auth/login',{method:'POST',body:JSON.stringify({username:(document.querySelector('#login-name') as HTMLInputElement).value,password:(document.querySelector('#login-password') as HTMLInputElement).value})});modalRoot.innerHTML='';document.body.classList.remove('logged-out');configureUser()}catch(err){document.querySelector('#login-error')!.textContent=(err as Error).message;button.disabled=false;button.textContent='Войти'}};requestAnimationFrame(()=>document.querySelector<HTMLInputElement>('#login-name')?.focus())}
async function init(){try{currentUser=await api<User>('/api/auth/me');document.body.classList.remove('logged-out');configureUser()}catch{showLogin()}}
init();
