type Employee={id:string;firstName:string;lastName:string;middleName:string;active:boolean};
type Contribution={name:string;value:number};
type HiredDetail={fullName:string;responsible:string};
type Row={id:string;officeId:string;officeName:string;sortOrder:number;openVacancies:number;invitationThreshold:number;invitedCandidates:number;interviewPlan:number;interviewedCandidates:number;interns:number;reserveCandidates:number;dismissedWorkers:number;efficiency:number;hiredWorkers:string[];hiredDetails?:HiredDetail[];contributions?:Record<string,Contribution[]>};
type Bootstrap={report:{id:string;date:string;status:string;editable:boolean;accessCount?:number};rows:Row[];norm:number;totals:Record<string,number>};
type User={id:string;employeeId?:string;username:string;role:'superadmin'|'admin'|'employee';firstName:string;lastName:string;middleName:string;active?:boolean};
type ReportAccessUser={id:string;firstName:string;lastName:string;middleName:string;accessUntil?:string};
const content=document.querySelector<HTMLElement>('#content')!;
const modalRoot=document.querySelector<HTMLElement>('#modal-root')!;
const datePickerRoot=document.querySelector<HTMLElement>('#date-picker-root')!;
const appTooltip=document.querySelector<HTMLElement>('#app-tooltip')!;
const title=document.querySelector<HTMLElement>('#page-title')!;
const subtitle=document.querySelector<HTMLElement>('#page-subtitle')!;
const nav=document.querySelector<HTMLElement>('#nav')!;
const icon=(body:string)=>`<svg viewBox="0 0 24 24" aria-hidden="true">${body}</svg>`;
const icons={
  report:icon('<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 21V9"/>'),
  history:icon('<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2M3 12H1"/>'),
  employees:icon('<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>'),
  offices:icon('<path d="M3 21h18M5 21V7l7-4 7 4v14M9 10h.01M15 10h.01M9 14h.01M15 14h.01M10 21v-3h4v3"/>'),
  imports:icon('<path d="M12 3v12M7 10l5 5 5-5M5 21h14"/>'),
  settings:icon('<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1 1.55V21h-4v-.08A1.7 1.7 0 0 0 9 19.37a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.63 15a1.7 1.7 0 0 0-1.55-1H3v-4h.08A1.7 1.7 0 0 0 4.63 9a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.63a1.7 1.7 0 0 0 1-1.55V3h4v.08A1.7 1.7 0 0 0 15 4.63a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.37 9a1.7 1.7 0 0 0 1.55 1H21v4h-.08A1.7 1.7 0 0 0 19.4 15z"/>'),
  audit:icon('<path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/>'),
  left:icon('<path d="m15 18-6-6 6-6"/>'),right:icon('<path d="m9 18 6-6-6-6"/>'),
  columns:icon('<path d="M4 4h16v16H4zM9 4v16M15 4v16"/>'),reset:icon('<path d="M3 12a9 9 0 1 0 3-6.7L3 8M3 3v5h5"/>'),
  fullscreen:icon('<path d="M8 3H3v5M16 3h5v5M8 21H3v-5M16 21h5v-5"/>'),download:icon('<path d="M12 3v12M7 10l5 5 5-5M5 21h14"/>'),check:icon('<path d="m5 12 4 4L19 6"/>'),
  search:icon('<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>'),
  access:icon('<circle cx="8" cy="15" r="4"/><path d="m11 12 8-8M15 8l3 3M17 6l2 2"/>'),
  calendar:icon('<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>')
};
const reportPage=[['report',icons.report,'Ежедневный отчёт']];
let pages:string[][]=reportPage;
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
const dateObject=(value:string)=>new Date(value+'T12:00:00');
const dateValue=(value:Date)=>value.toISOString().slice(0,10);
const isWeekend=(value:string)=>{const day=dateObject(value).getDay();return day===0||day===6};
function nearestBusinessDate(value:string,direction:-1|1=-1){const date=dateObject(value);while(date.getDay()===0||date.getDay()===6)date.setDate(date.getDate()+direction);return dateValue(date)}
const businessToday=()=>nearestBusinessDate(today(),-1);
const displayDate=(value:string)=>dateObject(value).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'});
let currentPage='report', reportDate=today(), report:Bootstrap|null=null, saveTimers=new Map<string,number>();
let modalKeyHandler:((event:KeyboardEvent)=>void)|null=null;
let datePickerOutsideHandler:((event:PointerEvent)=>void)|null=null,datePickerKeyHandler:((event:KeyboardEvent)=>void)|null=null;
let currentUser:User|null=null,adminUsers:User[]=[];
let selectedEmployee='';
let reportSocket:WebSocket|null=null,reportRefreshTimer=0;
const dirtyRows=new Set<string>();
const defaultColumnWidths:Record<string,number>={office:200,openVacancies:130,invitationThreshold:125,invitedCandidates:125,interviewPlan:125,interviewedCandidates:140,interns:125,reserveCandidates:125,hires:125,dismissedWorkers:125,efficiency:125};
const allColumns=[
  ['office','РП'],['openVacancies','Количество открытых вакансий'],['invitationThreshold','Минимальный порог приглашенных кандидатов'],
  ['invitedCandidates','Количество приглашенных кандидатов'],['interviewPlan','План на прошедших собеседование'],
  ['interviewedCandidates','Количество прошедших собеседование'],['interns','Количество кандидатов на стажировке'],
  ['reserveCandidates','Количество кандидатов в резерве'],['hires','Количество принятых работников'],
  ['dismissedWorkers','Количество уволенных работников'],['efficiency','Эффективность работников']
] as const;
let columnWidths:Record<string,number>=JSON.parse(localStorage.getItem('hr-column-widths-v2')||'{}');

function esc(v:unknown){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!))}
let tooltipTarget:HTMLElement|null=null,tooltipTimer=0;
function hideTooltip(){clearTimeout(tooltipTimer);tooltipTarget=null;appTooltip.classList.remove('show')}
function placeTooltip(e:PointerEvent){const gap=14,box=appTooltip.getBoundingClientRect();let left=e.clientX+gap,top=e.clientY+gap;if(left+box.width>innerWidth-8)left=e.clientX-box.width-gap;if(top+box.height>innerHeight-8)top=e.clientY-box.height-gap;appTooltip.style.left=Math.max(8,left)+'px';appTooltip.style.top=Math.max(8,top)+'px'}
document.addEventListener('pointerover',e=>{const el=(e.target as HTMLElement).closest<HTMLElement>('.sheet td[data-tooltip]');if(!el)return;const text=el.dataset.tooltip||'';if(!text)return;clearTimeout(tooltipTimer);tooltipTarget=el;appTooltip.textContent=text;placeTooltip(e);tooltipTimer=window.setTimeout(()=>{if(tooltipTarget===el)appTooltip.classList.add('show')},320)});
document.addEventListener('pointermove',e=>{if(tooltipTarget)placeTooltip(e)});
document.addEventListener('pointerout',e=>{if(!tooltipTarget)return;const next=e.relatedTarget as Node|null;if(!next||!tooltipTarget.contains(next))hideTooltip()});
document.addEventListener('scroll',()=>{hideTooltip();closeDatePicker()},true);
async function api<T=any>(url:string,options:RequestInit={}):Promise<T>{const res=await fetch(url,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(options.headers||{})}});if(!res.ok){let msg=`Ошибка ${res.status}`;try{msg=(await res.json()).error||msg}catch{}throw new Error(msg)}return res.status===204?null as T:res.json()}
let toastTimer=0;
function toast(message:string,error=false){
 const e=document.querySelector<HTMLElement>('#toast')!,duration=error?5200:3400;
 clearTimeout(toastTimer);e.className='toast';void e.offsetWidth;
 e.style.setProperty('--toast-duration',duration+'ms');e.setAttribute('role',error?'alert':'status');
 e.innerHTML=`<span class="toast-icon" aria-hidden="true">${error?icon('<circle cx="12" cy="12" r="9"/><path d="M12 7v6M12 17h.01"/>'):icons.check}</span><span class="toast-content"><strong>${error?'Ошибка':'Готово'}</strong><span>${esc(message)}</span></span><button class="toast-close" type="button" aria-label="Закрыть уведомление">×</button><span class="toast-progress" aria-hidden="true"></span>`;
 e.className='toast show'+(error?' error':' success');
 e.querySelector<HTMLButtonElement>('.toast-close')!.onclick=()=>{clearTimeout(toastTimer);e.classList.remove('show')};
 toastTimer=window.setTimeout(()=>e.classList.remove('show'),duration);
}
function setHeader(h:string,s:string){title.textContent=h;subtitle.textContent=s}
function drawNav(){nav.innerHTML=pages.map(([id,icon,label])=>`<button class="nav-item ${id===currentPage?'active':''}" data-page="${id}"><span class="nav-icon">${icon}</span><span class="nav-label">${label}</span></button>`).join('');nav.querySelectorAll<HTMLButtonElement>('[data-page]').forEach(b=>b.onclick=()=>{currentPage=b.dataset.page!;drawNav();route()})}
async function route(){closeDatePicker();content.classList.toggle('report-workspace',currentPage==='report');document.body.classList.toggle('report-page',currentPage==='report');if(currentPage!=='report'&&reportSocket){const old=reportSocket;reportSocket=null;old.close()}content.innerHTML='<div class="empty">Загрузка…</div>';try{if(currentPage==='report')await loadReport();else if(currentPage==='exports')await exportPage();else if(currentPage==='users')await usersPage();else if(currentPage==='offices')await officesPage();else if(currentPage==='settings')await settingsPage()}catch(e){content.innerHTML=`<div class="card empty">${esc((e as Error).message)}</div>`}}

const numeric:[keyof Row,string][]=[['openVacancies','Количество открытых вакансий'],['invitationThreshold','Минимальный порог приглашенных кандидатов'],['invitedCandidates','Количество приглашенных кандидатов'],['interviewPlan','План на прошедших собеседование'],['interviewedCandidates','Количество прошедших собеседование'],['interns','Количество кандидатов на стажировке'],['reserveCandidates','Количество кандидатов в резерве']];
function manager(){return currentUser?.role==='admin'||currentUser?.role==='superadmin'}
async function loadReport(){setHeader(manager()?'Сводный отчёт':'Мой ежедневный отчёт',manager()?'Суммарные показатели сотрудников':'Заполнение персональных показателей');rememberScroll();if(manager()){adminUsers=await api<User[]>(`/api/users?context=report&date=${encodeURIComponent(reportDate)}`);if(selectedEmployee&&!adminUsers.some(user=>user.id===selectedEmployee))selectedEmployee=''}const filter=manager()&&selectedEmployee?`&employeeId=${encodeURIComponent(selectedEmployee)}`:'';report=await api(`/api/bootstrap?date=${reportDate}${filter}`);renderReport()}
function reportEmployeeOptions(){const option=(u:User)=>`<option value="${u.id}" ${u.id===selectedEmployee?'selected':''}>${esc([u.lastName,u.firstName,u.middleName].filter(Boolean).join(' '))}</option>`;return `<option value="">Все сотрудники</option>${adminUsers.map(option).join('')}`}
function colClass(_id:string){return ''}
function defaultTableWidth(){const natural=Object.values(defaultColumnWidths).reduce((sum,width)=>sum+width,0);return Math.max(allColumns.length*80,Math.min(natural,content.clientWidth-24))}
function defaultColWidth(id:string){const index=allColumns.findIndex(([column])=>column===id),natural=Object.values(defaultColumnWidths).reduce((sum,width)=>sum+width,0),target=defaultTableWidth();if(index<0)return 125;const before=allColumns.slice(0,index).reduce((sum,[column])=>sum+(defaultColumnWidths[column]||125),0),after=before+(defaultColumnWidths[id]||125);return Math.round(after*target/natural)-Math.round(before*target/natural)}
function colWidth(id:string){return columnWidths[id]??defaultColWidth(id)}
function tableWidth(){return allColumns.reduce((width,[id])=>width+colWidth(id),0)}
function hasCustomColumnWidths(){return allColumns.some(([id])=>columnWidths[id]!==undefined&&columnWidths[id]!==defaultColWidth(id))}
function updateResetButtonVisibility(){const button=content.querySelector<HTMLButtonElement>('#reset-column-widths');if(button)button.hidden=!hasCustomColumnWidths()}
function alignTableWithToolbar(){const toolbar=content.querySelector<HTMLElement>('.toolbar'),wrap=content.querySelector<HTMLElement>('.sheet-wrap'),table=content.querySelector<HTMLTableElement>('.sheet');if(!toolbar||!wrap||!table)return;table.style.marginLeft=Math.max(0,toolbar.getBoundingClientRect().left-wrap.getBoundingClientRect().left)+'px'}
function headerCell(id:string,label:string){return `<th data-col="${id}"><span>${esc(label)}</span><span class="col-resizer" data-resize="${id}"></span></th>`}
function contributionTooltip(r:Row,key:string,total:number,percent=false){if(!manager())return '';const value=percent?total.toFixed(1)+'%':String(total);if(key==='openVacancies')return `Итого: ${value}\nОбщее значение для всех сотрудников`;const values=r.contributions?.[key]||[],details=values.length?values.map(x=>`${x.name || 'Сотрудник'} — ${percent?x.value.toFixed(1)+'%':x.value}`).join('\n'):'Нет заполненных отчётов';return `Итого: ${value}\n${details}`}
function hiredCell(r:Row,locked:boolean){if(!locked)return `<button class="cell nav-cell people hires">${r.hiredWorkers.length||0}</button>`;if(manager())return `<button class="cell people hires summary-hires">${r.hiredWorkers.length||0}</button>`;return `<span class="readonly-cell">${r.hiredWorkers.length}</span>`}
function wireSheetHighlighting(){
 const table=content.querySelector<HTMLTableElement>('.sheet');if(!table)return;
 let hoveredColumn='';
 const markColumn=(column:string,className:string,on:boolean)=>table.querySelectorAll<HTMLElement>(`[data-col="${column}"]`).forEach(cell=>cell.classList.toggle(className,on));
 const setHoveredColumn=(column:string)=>{if(column===hoveredColumn)return;if(hoveredColumn)markColumn(hoveredColumn,'hovered-column',false);hoveredColumn=column;if(column)markColumn(column,'hovered-column',true)};
 table.addEventListener('pointerover',event=>{const cell=(event.target as HTMLElement).closest<HTMLElement>('tbody td[data-col]');setHoveredColumn(cell?.dataset.col||'')});
 table.addEventListener('pointerleave',()=>setHoveredColumn(''));
 table.addEventListener('focusin',event=>{const cell=(event.target as HTMLElement).closest<HTMLElement>('td[data-col]');if(!cell)return;table.querySelectorAll('.active-column').forEach(el=>el.classList.remove('active-column'));markColumn(cell.dataset.col!,'active-column',true)});
 table.addEventListener('focusout',()=>requestAnimationFrame(()=>{const focused=document.activeElement as HTMLElement|null;if(focused&&table.contains(focused))return;table.querySelectorAll('.active-column').forEach(el=>el.classList.remove('active-column'))}));
}
function renderReport(){if(!report)return;const locked=!report.report.editable;const filtered=adminUsers.find(x=>x.id===selectedEmployee),isPast=reportDate<today(),isFuture=reportDate>today(),accessCount=report.report.accessCount||0;const accessButton=manager()&&reportDate!==today()?`<button class="btn btn-outline with-icon report-access-button ${accessCount?'has-access':''}" id="report-access" ${isFuture?'disabled title="Доступ нельзя открыть до наступления выбранной даты"':''}>${icons.access}<span>${accessCount?`Доступ открыт · ${accessCount}`:'Открыть доступ'}</span></button>`:'';content.innerHTML=`
 <div class="toolbar"><div class="date-switcher"><button class="btn icon-btn" id="prev-day" aria-label="Предыдущий рабочий день">${icons.left}</button><button class="report-date-button" id="report-date" type="button" aria-haspopup="dialog" aria-label="Выбрать дату отчёта"><span>${displayDate(reportDate)}</span>${icons.calendar}</button><button class="btn icon-btn" id="next-day" aria-label="Следующий рабочий день">${icons.right}</button></div>${manager()?`<select id="employee-filter">${reportEmployeeOptions()}</select>`:''}${locked&&!manager()?'<span class="readonly-note">Доступ закрыт</span>':''}${!manager()||selectedEmployee?`<div id="norm" class="norm">План 0 / ${report.norm}</div>`:''}${!locked?'<span id="save-state" class="save-state saved">Сохранено</span>':''}<div class="spacer"></div>${accessButton}<button class="btn btn-outline icon-btn" id="reset-column-widths" title="Сбросить ширину колонок" aria-label="Сбросить ширину колонок" ${hasCustomColumnWidths()?'':'hidden'}>${icons.reset}</button></div>
 <div class="sheet-wrap"><table class="sheet ${manager()?'manager-sheet':''}" style="width:${tableWidth()}px"><colgroup>${allColumns.map(([id])=>`<col data-col="${id}" class="${colClass(id)}" style="width:${colWidth(id)}px">`).join('')}</colgroup><thead><tr>${headerCell('office','РП')}${numeric.map(([k,label])=>headerCell(String(k),label)).join('')}${headerCell('hires','Количество принятых работников')}${headerCell('dismissedWorkers','Количество уволенных работников')}${headerCell('efficiency','Эффективность работников')}</tr></thead><tbody>
 ${report.rows.map((r,ri)=>`<tr data-row="${ri}"><td data-col="office" class="${colClass('office')}">${esc(r.officeName)}</td>${numeric.map(([k])=>`<td data-col="${k}" class="${colClass(String(k))}" data-tooltip="${esc(contributionTooltip(r,String(k),Number(r[k])))}"><input class="cell nav-cell" type="text" inputmode="numeric" pattern="[0-9]*" data-key="${k}" data-original="${r[k]}" value="${r[k]}" ${locked?'disabled':''}></td>`).join('')}<td data-col="hires" class="${colClass('hires')}" data-tooltip="${esc(contributionTooltip(r,'hiredWorkers',r.hiredWorkers.length))}">${hiredCell(r,locked)}</td><td data-col="dismissedWorkers" class="${colClass('dismissedWorkers')}" data-tooltip="${esc(contributionTooltip(r,'dismissedWorkers',r.dismissedWorkers))}"><input class="cell nav-cell" type="text" inputmode="numeric" pattern="[0-9]*" data-key="dismissedWorkers" data-original="${r.dismissedWorkers}" value="${r.dismissedWorkers}" ${locked?'disabled':''}></td><td data-col="efficiency" class="efficiency ${colClass('efficiency')}" data-tooltip="${esc(contributionTooltip(r,'efficiency',r.efficiency,true))}">${r.efficiency.toFixed(1)}%</td></tr>`).join('')}</tbody><tfoot><tr><td data-col="office" class="${colClass('office')}">ИТОГО</td>${numeric.map(([k])=>`<td data-col="${k}" class="${colClass(String(k))}" data-total="${k}">0</td>`).join('')}<td data-col="hires" class="${colClass('hires')}" data-total="hiredWorkers">0</td><td data-col="dismissedWorkers" class="${colClass('dismissedWorkers')}" data-total="dismissedWorkers">0</td><td data-col="efficiency" class="${colClass('efficiency')}" data-total="efficiency">0%</td></tr></tfoot></table></div>`;
 const dateButton=document.querySelector<HTMLButtonElement>('#report-date')!;dateButton.onclick=()=>openDatePicker(dateButton);
 document.querySelector<HTMLButtonElement>('#prev-day')!.onclick=()=>shiftDate(-1);document.querySelector<HTMLButtonElement>('#next-day')!.onclick=()=>shiftDate(1);
 document.querySelector<HTMLButtonElement>('#reset-column-widths')!.onclick=resetColumnWidths;
 const access=document.querySelector<HTMLButtonElement>('#report-access');if(access&&isPast)access.onclick=reportAccessModal;
 const employeeFilter=document.querySelector<HTMLSelectElement>('#employee-filter');if(employeeFilter)employeeFilter.onchange=()=>{selectedEmployee=employeeFilter.value;loadReport()};
 content.querySelectorAll<HTMLTableRowElement>('tbody tr').forEach(tr=>{const i=Number(tr.dataset.row),r=report!.rows[i];tr.querySelectorAll<HTMLInputElement>('input[data-key]:not(:disabled)').forEach(inp=>wireNumericInput(inp,r,tr));const hires=tr.querySelector<HTMLButtonElement>('.hires');if(hires)hires.onclick=()=>manager()&&locked?hiredSummaryModal(r):hiresModal(r,tr);tr.querySelectorAll<HTMLElement>('.nav-cell').forEach(x=>{x.addEventListener('focus',()=>tr.classList.add('active-row'));x.addEventListener('blur',()=>{if(!tr.contains(document.activeElement))tr.classList.remove('active-row')})})});wireSheetHighlighting();keyboardNav();setupColumnResizing();alignTableWithToolbar();recalc();restoreScroll();connectReportSocket()}
function fullName(e:Employee){return [e.lastName,e.firstName,e.middleName].filter(Boolean).join(' ')}
function recalc(){if(!report)return;const keys=[...numeric.map(x=>x[0]),'dismissedWorkers'] as (keyof Row)[];keys.forEach(k=>{const n=report!.rows.reduce((s,r)=>s+Number(r[k]||0),0);const el=content.querySelector(`[data-total="${k}"]`);if(el)el.textContent=String(n)});const hires=report.rows.reduce((s,r)=>s+r.hiredWorkers.length,0);content.querySelector('[data-total="hiredWorkers"]')!.textContent=String(hires);const plan=report.rows.reduce((s,r)=>s+r.interviewPlan,0),interns=report.rows.reduce((s,r)=>s+r.interns,0);content.querySelector('[data-total="efficiency"]')!.textContent=(plan?interns*100/plan:0).toFixed(1)+'%';const norm=content.querySelector<HTMLElement>('#norm');if(norm){const sum=report.rows.reduce((s,r)=>s+r.invitationThreshold,0);norm.textContent=`План ${sum} / ${report.norm}`;norm.classList.toggle('ok',sum>=report.norm)}}
function rowPayload(r:Row){return{openVacancies:r.openVacancies,invitationThreshold:r.invitationThreshold,invitedCandidates:r.invitedCandidates,interviewPlan:r.interviewPlan,interviewedCandidates:r.interviewedCandidates,interns:r.interns,reserveCandidates:r.reserveCandidates,dismissedWorkers:r.dismissedWorkers,responsibleIds:[],hiredWorkers:r.hiredWorkers}}
function setSaveState(state:'saving'|'saved'|'failed',message?:string){const el=content.querySelector<HTMLElement>('#save-state');if(!el)return;el.className=`save-state ${state}`;el.textContent=message||(state==='saving'?'Сохранение...':state==='saved'?'Сохранено':'Ошибка сохранения')}
function scheduleSave(r:Row,tr:HTMLTableRowElement){dirtyRows.add(r.id);setSaveState('saving');clearTimeout(saveTimers.get(r.id));saveTimers.set(r.id,window.setTimeout(()=>saveRow(r,tr),500))}
async function saveRow(r:Row,tr:HTMLTableRowElement){clearTimeout(saveTimers.get(r.id));saveTimers.delete(r.id);setSaveState('saving');try{const x=await api<{efficiency:number}>(`/api/report/rows/${r.id}`,{method:'PUT',body:JSON.stringify(rowPayload(r))});r.efficiency=x.efficiency;const eff=tr.querySelector<HTMLElement>('[data-col="efficiency"]');if(eff)eff.textContent=x.efficiency.toFixed(1)+'%';dirtyRows.delete(r.id);tr.querySelectorAll<HTMLInputElement>('input[data-key]').forEach(i=>{i.dataset.original=i.value||'0';i.classList.remove('invalid')});setSaveState(dirtyRows.size?'saving':'saved')}catch(e){const message=(e as Error).message;setSaveState('failed',message);tr.querySelectorAll<HTMLInputElement>('input[data-key]').forEach(i=>i.classList.add('invalid'));toast(message,true)}}
async function completeReport(){if(!report)return;try{await Promise.all(report.rows.filter(r=>dirtyRows.has(r.id)).map(r=>{const tr=content.querySelector<HTMLTableRowElement>(`tr[data-row="${report!.rows.indexOf(r)}"]`)!;return saveRow(r,tr)}));await api(`/api/reports/${report.report.id}/complete`,{method:'POST',body:'{}'});toast('Отчёт успешно завершён');await loadReport()}catch(e){toast((e as Error).message,true)}}
function wireNumericInput(inp:HTMLInputElement,r:Row,tr:HTMLTableRowElement){inp.onfocus=()=>{inp.dataset.original=inp.value;if(inp.value==='0')inp.value='';else inp.select();tr.classList.add('active-row')};inp.onbeforeinput=e=>{const ev=e as InputEvent;if(ev.data&&!/^\d+$/.test(ev.data))e.preventDefault()};inp.onpaste=e=>{const text=e.clipboardData?.getData('text')||'';if(!/^\d+$/.test(text.trim())){e.preventDefault();inp.classList.add('invalid');toast('Разрешены только целые неотрицательные числа',true);setTimeout(()=>inp.classList.remove('invalid'),1200)}};inp.oninput=()=>{const clean=inp.value.replace(/[^0-9]/g,'');if(inp.value!==clean){inp.value=clean;inp.classList.add('invalid')}else inp.classList.remove('invalid');(r as any)[inp.dataset.key!]=clean===''?0:Number(clean);if(inp.dataset.key==='interns'||inp.dataset.key==='interviewPlan'){r.efficiency=r.interviewPlan?100*r.interns/r.interviewPlan:0;const eff=tr.querySelector<HTMLElement>('[data-col="efficiency"]');if(eff)eff.textContent=r.efficiency.toFixed(1)+'%'}recalc();scheduleSave(r,tr)};inp.onblur=()=>{if(inp.value===''){inp.value='0';(r as any)[inp.dataset.key!]=0}if(!tr.contains(document.activeElement))tr.classList.remove('active-row')}}
function keyboardNav(){const cells=[...content.querySelectorAll<HTMLElement>('.nav-cell')].filter(x=>x.offsetParent!==null&&!('disabled' in x&&(x as HTMLInputElement).disabled));const perRow=report?cells.length/report.rows.length:1;cells.forEach((c,i)=>c.onkeydown=e=>{if(e.key==='Escape'&&c instanceof HTMLInputElement){e.preventDefault();c.value=c.dataset.original||'0';const tr=c.closest<HTMLTableRowElement>('tr')!,r=report!.rows[Number(tr.dataset.row)];(r as any)[c.dataset.key!]=Number(c.value);clearTimeout(saveTimers.get(r.id));dirtyRows.delete(r.id);recalc();c.blur();setSaveState(dirtyRows.size?'saving':'saved');return}let next=-1;if(e.key==='Enter'){e.preventDefault();const tr=c.closest<HTMLTableRowElement>('tr')!,r=report!.rows[Number(tr.dataset.row)];void saveRow(r,tr);next=i+1}else if(e.key==='ArrowRight')next=i+1;else if(e.key==='ArrowLeft')next=i-1;else if(e.key==='ArrowDown')next=i+perRow;else if(e.key==='ArrowUp')next=i-perRow;if(next>=0&&next<cells.length){e.preventDefault();cells[next].focus();if(cells[next] instanceof HTMLInputElement)(cells[next] as HTMLInputElement).select()}})}

function closeDatePicker(){datePickerRoot.innerHTML='';if(datePickerOutsideHandler){document.removeEventListener('pointerdown',datePickerOutsideHandler);datePickerOutsideHandler=null}if(datePickerKeyHandler){document.removeEventListener('keydown',datePickerKeyHandler);datePickerKeyHandler=null}}
function openDatePicker(anchor:HTMLElement){
 closeDatePicker();let month=dateObject(reportDate);month=new Date(month.getFullYear(),month.getMonth(),1,12);
 const draw=()=>{const year=month.getFullYear(),monthIndex=month.getMonth(),first=new Date(year,monthIndex,1,12),days=new Date(year,monthIndex+1,0,12).getDate(),offset=(first.getDay()+6)%7,total=Math.ceil((offset+days)/7)*7,monthTitle=month.toLocaleDateString('ru-RU',{month:'long',year:'numeric'});let cells='';for(let index=0;index<total;index++){const day=index-offset+1;if(day<1||day>days){cells+='<span class="calendar-empty"></span>';continue}const value=dateValue(new Date(year,monthIndex,day,12)),weekend=isWeekend(value);cells+=`<button class="calendar-day ${weekend?'weekend':''} ${value===reportDate?'selected':''} ${value===today()?'current':''}" type="button" data-date="${value}" ${weekend?'disabled aria-label="Выходной день"':''}>${day}</button>`}datePickerRoot.innerHTML=`<div class="date-picker" role="dialog" aria-label="Выбор даты отчёта"><div class="calendar-head"><button type="button" class="calendar-nav calendar-prev" aria-label="Предыдущий месяц">${icons.left}</button><strong>${esc(monthTitle)}</strong><button type="button" class="calendar-nav calendar-next" aria-label="Следующий месяц">${icons.right}</button></div><div class="calendar-weekdays"><span>Пн</span><span>Вт</span><span>Ср</span><span>Чт</span><span>Пт</span><span class="weekend">Сб</span><span class="weekend">Вс</span></div><div class="calendar-grid">${cells}</div><div class="calendar-foot"><span><i></i>Сегодня</span><small>Сб и Вс — выходные</small></div></div>`;const picker=datePickerRoot.firstElementChild as HTMLElement,rect=anchor.getBoundingClientRect(),width=picker.offsetWidth||304,left=Math.max(8,Math.min(rect.left,innerWidth-width-8)),height=picker.offsetHeight||360,top=rect.bottom+6+height>innerHeight?Math.max(8,rect.top-height-6):rect.bottom+6;picker.style.left=left+'px';picker.style.top=top+'px';picker.querySelector<HTMLButtonElement>('.calendar-prev')!.onclick=()=>{month=new Date(year,monthIndex-1,1,12);draw()};picker.querySelector<HTMLButtonElement>('.calendar-next')!.onclick=()=>{month=new Date(year,monthIndex+1,1,12);draw()};picker.querySelectorAll<HTMLButtonElement>('.calendar-day:not(:disabled)').forEach(button=>button.onclick=()=>{const value=button.dataset.date!;closeDatePicker();changeDate(value)})};
 draw();requestAnimationFrame(()=>{datePickerOutsideHandler=event=>{if(!datePickerRoot.contains(event.target as Node)&&!anchor.contains(event.target as Node))closeDatePicker()};document.addEventListener('pointerdown',datePickerOutsideHandler!)});datePickerKeyHandler=event=>{if(event.key==='Escape'){event.preventDefault();closeDatePicker();anchor.focus()}};document.addEventListener('keydown',datePickerKeyHandler)
}
function changeDate(value:string){if(isWeekend(value))return;closeDatePicker();rememberScroll();reportDate=value;loadReport()}
function shiftDate(days:number){const direction=days<0?-1:1,date=dateObject(reportDate);do{date.setDate(date.getDate()+direction)}while(date.getDay()===0||date.getDay()===6);changeDate(dateValue(date))}
function rememberScroll(){const el=content.querySelector<HTMLElement>('.sheet-wrap');if(el)sessionStorage.setItem(`hr-scroll-${reportDate}`,JSON.stringify({top:el.scrollTop,left:el.scrollLeft}))}
function restoreScroll(){requestAnimationFrame(()=>{const el=content.querySelector<HTMLElement>('.sheet-wrap');if(!el)return;const pos=JSON.parse(sessionStorage.getItem(`hr-scroll-${reportDate}`)||'{"top":0,"left":0}');el.scrollTop=pos.top;el.scrollLeft=pos.left;el.onscroll=()=>sessionStorage.setItem(`hr-scroll-${reportDate}`,JSON.stringify({top:el.scrollTop,left:el.scrollLeft}))})}
function connectReportSocket(){if(reportSocket){const old=reportSocket;reportSocket=null;old.close()}const socketDate=reportDate,ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/reports?date=${encodeURIComponent(socketDate)}`);reportSocket=ws;ws.onmessage=e=>{const event=JSON.parse(e.data);if(event.date!==reportDate)return;if(event.type==='report_access_changed'){if(!manager()&&event.userIds?.includes(currentUser?.id))loadReport();return}if(event.type!=='report_updated')return;if(manager()){clearTimeout(reportRefreshTimer);reportRefreshTimer=window.setTimeout(()=>loadReport(),250);return}if(event.field==='openVacancies'&&report){const index=report.rows.findIndex(r=>r.officeId===event.officeId);if(index<0)return;const row=report.rows[index];row.openVacancies=Number(event.value)||0;const input=content.querySelector<HTMLInputElement>(`tr[data-row="${index}"] input[data-key="openVacancies"]`);if(input){input.value=String(row.openVacancies);input.dataset.original=input.value}recalc()}};ws.onclose=()=>{if(reportSocket===ws){reportSocket=null;if(currentPage==='report'&&reportDate===socketDate)setTimeout(connectReportSocket,1500)}}}
function setupColumnResizing(){content.querySelectorAll<HTMLElement>('[data-resize]').forEach(handle=>handle.onpointerdown=e=>{e.preventDefault();const id=handle.dataset.resize!,col=content.querySelector<HTMLElement>(`col[data-col="${id}"]`)!,table=content.querySelector<HTMLTableElement>('.sheet')!,start=e.clientX,startWidth=col.getBoundingClientRect().width,startTableWidth=table.getBoundingClientRect().width;const move=(ev:PointerEvent)=>{const width=Math.round(Math.max(80,Math.min(320,startWidth+ev.clientX-start)));col.style.width=width+'px';table.style.width=startTableWidth+width-startWidth+'px';columnWidths[id]=width;updateResetButtonVisibility()};const up=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);if(hasCustomColumnWidths())localStorage.setItem('hr-column-widths-v2',JSON.stringify(columnWidths));else localStorage.removeItem('hr-column-widths-v2')};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up)})}
function applyColumnWidths(){content.querySelectorAll<HTMLElement>('col[data-col]').forEach(col=>{col.style.width=colWidth(col.dataset.col!)+'px'});const table=content.querySelector<HTMLTableElement>('.sheet');if(table)table.style.width=tableWidth()+'px';alignTableWithToolbar()}
function resetColumnWidths(){columnWidths={};localStorage.removeItem('hr-column-widths-v2');applyColumnWidths();updateResetButtonVisibility()}

function accessFullName(user:ReportAccessUser){return [user.lastName,user.firstName,user.middleName].filter(Boolean).join(' ')}
function accessUntilLabel(value:string){return new Date(value).toLocaleString('ru-RU',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}
async function reportAccessModal(){
 try{
  const users=await api<ReportAccessUser[]>(`/api/report-access?date=${encodeURIComponent(reportDate)}`),active=users.filter(user=>user.accessUntil),available=users.filter(user=>!user.accessUntil);
  const activeMarkup=active.length?`<section class="access-section"><div class="access-section-head"><b>Доступ открыт</b><span>${active.length}</span></div><div class="access-current-list">${active.map(user=>`<div class="access-current"><span class="access-avatar">${esc((user.firstName?.[0]||'')+(user.lastName?.[0]||''))}</span><span class="access-person"><b>${esc(accessFullName(user))}</b><small>До ${esc(accessUntilLabel(user.accessUntil!))}</small></span><button class="btn btn-danger close-access" type="button" data-id="${user.id}">Закрыть</button></div>`).join('')}</div></section>`:'';
  const availableMarkup=available.length?`<section class="access-section"><div class="access-section-head"><b>Выберите сотрудников</b><button class="access-select-all" type="button">Выбрать всех</button></div><div class="access-check-list">${available.map(user=>`<label class="access-check"><input type="checkbox" value="${user.id}"><span class="access-avatar">${esc((user.firstName?.[0]||'')+(user.lastName?.[0]||''))}</span><span>${esc(accessFullName(user))}</span></label>`).join('')}</div></section>`:`<div class="access-empty">Всем активным сотрудникам доступ уже открыт</div>`;
  showModal('Доступ к отчёту',`<div class="access-intro"><span class="access-date">${new Date(reportDate+'T00:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})}</span><p>Выбранные сотрудники смогут редактировать свой отчёт в течение 24 часов.</p></div>${activeMarkup}${availableMarkup}`,async()=>{
   const userIds=[...document.querySelectorAll<HTMLInputElement>('.access-check input:checked')].map(input=>input.value);if(!userIds.length)return;
   try{await api('/api/report-access',{method:'POST',body:JSON.stringify({date:reportDate,userIds})});closeModal();toast(`Доступ открыт на 24 часа: ${userIds.length}`);await loadReport()}catch(error){toast((error as Error).message,true)}
  },()=>{
   const save=document.querySelector<HTMLButtonElement>('.modal .save')!;save.textContent='Открыть доступ';save.disabled=true;
   const checks=[...document.querySelectorAll<HTMLInputElement>('.access-check input')],sync=()=>save.disabled=!checks.some(input=>input.checked);checks.forEach(input=>input.onchange=sync);
   const selectAll=document.querySelector<HTMLButtonElement>('.access-select-all');if(selectAll)selectAll.onclick=()=>{const allSelected=checks.every(input=>input.checked);checks.forEach(input=>input.checked=!allSelected);selectAll.textContent=allSelected?'Выбрать всех':'Снять выбор';sync()};
   document.querySelectorAll<HTMLButtonElement>('.close-access').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await api('/api/report-access',{method:'DELETE',body:JSON.stringify({date:reportDate,userIds:[button.dataset.id]})});closeModal();toast('Доступ закрыт');await loadReport()}catch(error){button.disabled=false;toast((error as Error).message,true)}});
   if(!available.length)save.hidden=true;
  });
 }catch(error){toast((error as Error).message,true)}
}

function hiredSummaryModal(r:Row){const details=r.hiredDetails||[],groups=new Map<string,string[]>();details.forEach(x=>{const owner=x.responsible||'Сотрудник не указан';groups.set(owner,[...(groups.get(owner)||[]),x.fullName])});let body='';if(groups.size){body=`<div class="summary-count"><span>Всего принято по РП</span><b>${details.length}</b></div><div class="hired-summary">${[...groups].map(([owner,names])=>`<section class="hired-group"><div class="hired-owner"><span class="owner-avatar">${esc(owner.trim()[0]||'?')}</span><div><b>${esc(owner)}</b><small>Сотрудник, заполнивший отчёт · ${names.length}</small></div></div><div class="hired-names">${names.map((name,index)=>`<div><span class="hire-number">${index+1}</span><span>${esc(name)}</span></div>`).join('')}</div></section>`).join('')}</div>`}else{const contributions=(r.contributions?.hiredWorkers||[]).filter(x=>x.value>0);body=contributions.length?`<div class="summary-count"><span>Всего принято по РП</span><b>${r.hiredWorkers.length}</b></div><div class="hired-summary">${contributions.map(x=>`<section class="hired-group"><div class="hired-owner"><span class="owner-avatar">${esc(x.name.trim()[0]||'?')}</span><div><b>${esc(x.name)}</b><small>Сотрудник, заполнивший отчёт · ${x.value}</small></div></div></section>`).join('')}</div>`:'<div class="modal-empty">Принятых работников по этому РП нет</div>'}showInfoModal(`Принятые работники · ${r.officeName}`,body)}
function hiresModal(r:Row,tr:HTMLTableRowElement){let names=r.hiredWorkers.length?[...r.hiredWorkers]:[''];const body=()=>`<div class="modal-intro"><b>Принятые работники</b><span>Укажите полное ФИО каждого принятого работника</span></div><div id="hire-list">${names.map((n,i)=>`<div class="hire-row"><span class="hire-index">${i+1}</span><input class="input hire-input" data-i="${i}" value="${esc(n)}" placeholder="Фамилия Имя Отчество"><button class="remove-hire" data-i="${i}" aria-label="Удалить">×</button></div>`).join('')}</div><button id="add-hire" class="add-row-button">+ Добавить   </button>`;showModal('Количество принятых работников',body(),async()=>{names=[...document.querySelectorAll<HTMLInputElement>('.hire-input')].map(x=>x.value.trim()).filter(Boolean);r.hiredWorkers=names;tr.querySelector<HTMLButtonElement>('.hires')!.textContent=String(names.length);recalc();await saveNow(r,tr)},wire);function wire(){document.querySelector<HTMLButtonElement>('#add-hire')!.onclick=()=>{names=[...document.querySelectorAll<HTMLInputElement>('.hire-input')].map(x=>x.value);names.push('');document.querySelector('.modal-body')!.innerHTML=body();wire();requestAnimationFrame(()=>{const inputs=document.querySelectorAll<HTMLInputElement>('.hire-input');inputs[inputs.length-1]?.focus()})};document.querySelectorAll<HTMLButtonElement>('.remove-hire').forEach(b=>b.onclick=()=>{names=[...document.querySelectorAll<HTMLInputElement>('.hire-input')].map(x=>x.value);names.splice(Number(b.dataset.i),1);if(!names.length)names=[''];document.querySelector('.modal-body')!.innerHTML=body();wire()})}}
async function saveNow(r:Row,tr:HTMLTableRowElement){setSaveState('saving');try{const x=await api<{efficiency:number}>(`/api/report/rows/${r.id}`,{method:'PUT',body:JSON.stringify(rowPayload(r))});r.efficiency=x.efficiency;const eff=tr.querySelector<HTMLElement>('[data-col="efficiency"]');if(eff)eff.textContent=x.efficiency.toFixed(1)+'%';dirtyRows.delete(r.id);setSaveState(dirtyRows.size?'saving':'saved');closeModal();toast('Сохранено')}catch(e){setSaveState('failed');toast((e as Error).message,true)}}

function showModal(name:string,body:string,onSave:()=>void|Promise<void>,after?:()=>void){closeModal();modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true" aria-label="${esc(name)}"><div class="modal-head"><h2>${esc(name)}</h2><button class="close" aria-label="Закрыть">×</button></div><div class="modal-body">${body}</div><div class="modal-foot"><span class="modal-hint">Esc — закрыть · Ctrl+Enter — сохранить</span><button class="btn btn-outline cancel">Отмена</button><button class="btn btn-primary save">Сохранить</button></div></div></div>`;modalRoot.querySelectorAll<HTMLElement>('.close,.cancel').forEach(x=>x.onclick=closeModal);const save=modalRoot.querySelector<HTMLButtonElement>('.save')!;save.onclick=()=>onSave();modalKeyHandler=e=>{if(e.key==='Escape'){e.preventDefault();closeModal()}else if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();save.click()}};document.addEventListener('keydown',modalKeyHandler);after?.();requestAnimationFrame(()=>modalRoot.querySelector<HTMLElement>('input,button,select')?.focus())}
function showInfoModal(name:string,body:string){closeModal();modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal summary-modal" role="dialog" aria-modal="true" aria-label="${esc(name)}"><div class="modal-head"><h2>${esc(name)}</h2><button class="close" aria-label="Закрыть">×</button></div><div class="modal-body">${body}</div><div class="modal-foot"><button class="btn btn-primary close-info">Закрыть</button></div></div></div>`;modalRoot.querySelectorAll<HTMLElement>('.close,.close-info').forEach(x=>x.onclick=closeModal);modalKeyHandler=e=>{if(e.key==='Escape'){e.preventDefault();closeModal()}};document.addEventListener('keydown',modalKeyHandler)}
function closeModal(){if(modalKeyHandler){document.removeEventListener('keydown',modalKeyHandler);modalKeyHandler=null}modalRoot.innerHTML=''}
function download(url:string){location.href=url}

async function historyPage(){setHeader('История отчётов','Архив и выгрузка отчётов за период');const from=new Date(Date.now()-30*86400000).toISOString().slice(0,10),to=today();content.innerHTML=`<div class="toolbar"><div class="field"><label>С даты</label><input id="from" class="input" type="date" value="${from}"></div><div class="field"><label>По дату</label><input id="to" class="input" type="date" value="${to}"></div><button id="find" class="btn btn-primary">Показать</button><div class="spacer"></div><button id="period-export" class="btn btn-outline">Выгрузить период</button></div><div class="card"><div id="history-list"></div></div>`;const load=async()=>{const f=(document.querySelector('#from') as HTMLInputElement).value,t=(document.querySelector('#to') as HTMLInputElement).value,rows=await api<any[]>(`/api/reports/history?from=${f}&to=${t}`);document.querySelector('#history-list')!.innerHTML=rows.length?`<table class="data-table"><thead><tr><th>Дата</th><th>Статус</th><th>Порог</th><th>Приглашено</th><th>Стажёры</th><th>Принято</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.date}</td><td><span class="status-pill ${x.status}">${x.status==='completed'?'Завершён':'Черновик'}</span></td><td>${x.threshold}</td><td>${x.invited}</td><td>${x.interns}</td><td>${x.hires}</td><td><button class="btn btn-outline open-report" data-date="${x.date}">Открыть</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">За выбранный период отчётов нет</div>';document.querySelectorAll<HTMLButtonElement>('.open-report').forEach(b=>b.onclick=()=>{reportDate=b.dataset.date!;currentPage='report';drawNav();route()})};document.querySelector<HTMLButtonElement>('#find')!.onclick=load;document.querySelector<HTMLButtonElement>('#period-export')!.onclick=()=>download(`/api/reports/export?from=${(document.querySelector('#from') as HTMLInputElement).value}&to=${(document.querySelector('#to') as HTMLInputElement).value}`);await load()}

async function employeesPage(){setHeader('Сотрудники','Справочник сотрудников и массовый импорт');const rows=await api<Employee[]>('/api/employees');content.innerHTML=`<div class="card"><div class="card-head"><h2>Сотрудники <span class="muted">${rows.length}</span></h2><div><button id="template" class="btn btn-outline">Скачать шаблон</button> <button id="import" class="btn btn-outline">Импорт XLSX</button> <button id="new-employee" class="btn btn-primary">+ Добавить</button></div></div><table class="data-table"><thead><tr><th>Фамилия</th><th>Имя</th><th>Отчество</th><th>Статус</th><th></th></tr></thead><tbody>${rows.map(e=>`<tr><td>${esc(e.lastName)}</td><td>${esc(e.firstName)}</td><td>${esc(e.middleName)}</td><td>${e.active?'Активен':'Архив'}</td><td><button class="btn btn-outline edit-employee" data-id="${e.id}">Изменить</button></td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">Добавьте первого сотрудника</div>'}</div>`;document.querySelector<HTMLButtonElement>('#template')!.onclick=()=>download('/api/employees/template');document.querySelector<HTMLButtonElement>('#import')!.onclick=importModal;document.querySelector<HTMLButtonElement>('#new-employee')!.onclick=()=>employeeModal();document.querySelectorAll<HTMLButtonElement>('.edit-employee').forEach(b=>b.onclick=()=>employeeModal(rows.find(x=>x.id===b.dataset.id)))}
function employeeModal(e?:Employee){showModal(e?'Редактировать сотрудника':'Новый сотрудник',`<div class="grid-form"><div class="field"><label>Фамилия</label><input id="last" class="input" value="${esc(e?.lastName||'')}"></div><div class="field"><label>Имя</label><input id="first" class="input" value="${esc(e?.firstName||'')}"></div><div class="field"><label>Отчество</label><input id="middle" class="input" value="${esc(e?.middleName||'')}"></div></div>`,async()=>{const x={lastName:(document.querySelector('#last') as HTMLInputElement).value,firstName:(document.querySelector('#first') as HTMLInputElement).value,middleName:(document.querySelector('#middle') as HTMLInputElement).value,active:e?.active??true};await api(e?`/api/employees/${e.id}`:'/api/employees',{method:e?'PUT':'POST',body:JSON.stringify(x)});closeModal();toast('Сотрудник сохранён');employeesPage()})}
function importModal(){showModal('Импорт сотрудников',`<p class="muted">XLSX должен содержать строго три колонки: <b>Имя, Фамилия, Отчество</b>.</p><input id="import-file" class="input" type="file" accept=".xlsx"><div id="import-progress" style="display:none;margin-top:18px"><div class="progress"><span style="width:0"></span></div><p id="progress-text"></p><div class="error-list"></div></div>`,async()=>{const file=(document.querySelector('#import-file') as HTMLInputElement).files?.[0];if(!file){toast('Выберите файл',true);return}const fd=new FormData();fd.append('file',file);const x=await api<{id:string}>('/api/imports/employees',{method:'POST',body:fd});const box=document.querySelector<HTMLElement>('#import-progress')!;box.style.display='block';const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/imports/${x.id}`);ws.onmessage=ev=>{const p=JSON.parse(ev.data),percent=p.total?Math.round(p.processed*100/p.total):0;(box.querySelector('.progress span') as HTMLElement).style.width=percent+'%';box.querySelector('#progress-text')!.textContent=`Обработано ${p.processed} из ${p.total}, импортировано ${p.imported}`;box.querySelector('.error-list')!.innerHTML=(p.errors||[]).map((e:any)=>`Строка ${e.row}: ${esc(e.message)}`).join('<br>');if(p.status==='completed'||p.status==='failed'){ws.close();toast(p.status==='completed'?'Импорт завершён':'Ошибка импорта',p.status==='failed')}};document.querySelector<HTMLButtonElement>('.modal .save')!.disabled=true})}

async function usersPage(){setHeader('Пользователи','Сотрудники, роли и данные для входа');const rows=await api<User[]>('/api/users'),name=(u:User)=>[u.lastName,u.firstName,u.middleName].filter(Boolean).join(' ');content.innerHTML=`<div class="card admin-card"><div class="card-head"><div class="list-heading"><h2>Пользователи</h2><span>${rows.length} активных учётных записей</span></div><div class="page-actions"><label class="table-search">${icons.search}<input id="user-search" type="search" placeholder="Найти по ФИО или логину" aria-label="Поиск пользователей"></label><button id="new-user" class="btn btn-primary">+ Добавить сотрудника</button></div></div><div class="table-scroll"><table class="data-table"><thead><tr><th>ФИО</th><th>Логин</th><th>Роль</th><th>Статус</th><th class="actions-col">Действия</th></tr></thead><tbody>${rows.map(u=>`<tr data-search="${esc((name(u)+' '+u.username).toLowerCase())}"><td class="primary-cell">${esc(name(u))}</td><td><span class="login-value">${esc(u.username)}</span></td><td><span class="role-badge ${u.role}">${u.role==='admin'?'Администратор':'Сотрудник'}</span></td><td><span class="state-badge active"><i></i>Активен</span></td><td class="row-actions"><button class="btn btn-outline edit-user" data-id="${u.id}">Изменить</button><button class="btn btn-danger delete-user" data-id="${u.id}">Удалить</button></td></tr>`).join('')}</tbody></table></div>${rows.length?'':'<div class="empty">Добавьте первого сотрудника</div>'}<div class="filter-empty" hidden>По вашему запросу ничего не найдено</div></div>`;const search=document.querySelector<HTMLInputElement>('#user-search')!;search.oninput=()=>filterRows(search.value);document.querySelector<HTMLButtonElement>('#new-user')!.onclick=()=>userModal();document.querySelectorAll<HTMLButtonElement>('.edit-user').forEach(b=>b.onclick=()=>userModal(rows.find(x=>x.id===b.dataset.id)));document.querySelectorAll<HTMLButtonElement>('.delete-user').forEach(b=>b.onclick=async()=>{const u=rows.find(x=>x.id===b.dataset.id)!;if(!confirm(`Удалить учётную запись ${u.username}? Восстановить сотрудника будет нельзя.`))return;try{await api(`/api/users/${u.id}`,{method:'DELETE'});toast('Сотрудник удалён');await usersPage()}catch(e){toast((e as Error).message,true)}})}
async function exportPage(){setHeader('Выгрузка','Сводные показатели за выбранный период');const from=today(),to=today();content.innerHTML=`<div class="card export-panel"><div class="card-head"><h2>Выгрузка XLSX за период</h2></div><div class="panel-body"><div class="export-form"><div class="field"><label>Дата начала</label><input id="export-from" class="input" type="date" value="${from}"></div><div class="field"><label>Дата окончания</label><input id="export-to" class="input" type="date" value="${to}"></div></div><div class="export-note"><b>Сводный отчёт</b><span>Первый лист повторяет структуру образца HR.xlsx из 12 колонок. Показатели суммируются за выбранный период.</span></div><div class="export-note"><b>Принятые сотрудники</b><span>Второй лист содержит РП, ФИО принятого сотрудника и ответственного. Удалённые пользователи полностью исключаются из обоих листов.</span></div></div><div class="panel-actions"><button id="download-period" class="btn btn-primary with-icon">${icons.download}<span>Скачать XLSX</span></button></div></div>`;document.querySelector<HTMLButtonElement>('#download-period')!.onclick=()=>{const start=(document.querySelector('#export-from') as HTMLInputElement).value,end=(document.querySelector('#export-to') as HTMLInputElement).value;if(!start||!end||start>end){toast('Укажите корректный период',true);return}download(`/api/reports/export?from=${encodeURIComponent(start)}&to=${encodeURIComponent(end)}`)}}
function userModal(u?:User){const canChooseRole=currentUser?.role==='superadmin';showModal(u?'Изменить пользователя':'Новый пользователь',`<div class="user-form"><section class="form-section"><div class="form-section-head"><b>Данные сотрудника</b><span>ФИО отображается в отчётах и подсказках таблицы</span></div><div class="person-grid"><div class="field"><label>Фамилия</label><input id="user-last" class="input" placeholder="Например, Иванов" value="${esc(u?.lastName||'')}"></div><div class="field"><label>Имя</label><input id="user-first" class="input" placeholder="Иван" value="${esc(u?.firstName||'')}"></div><div class="field"><label>Отчество</label><input id="user-middle" class="input" placeholder="Иванович" value="${esc(u?.middleName||'')}"></div></div></section><section class="form-section"><div class="form-section-head"><b>Доступ к системе</b><span>Логин должен быть уникальным, пароль — не короче 8 символов</span></div><div class="access-grid"><div class="field"><label>Логин</label><input id="user-login" class="input" autocomplete="off" placeholder="Логин для входа" value="${esc(u?.username||'')}"></div><div class="field"><label>${u?'Новый пароль':'Пароль'}</label><input id="user-password" class="input" type="password" autocomplete="new-password" placeholder="${u?'Оставьте пустым, чтобы не менять':'Минимум 8 символов'}"></div><div class="field"><label>Роль</label><select id="user-role" ${canChooseRole?'':'disabled'}><option value="employee">Сотрудник</option>${canChooseRole?'<option value="admin">Администратор</option>':''}</select></div></div></section></div>`,async()=>{const payload={lastName:(document.querySelector('#user-last') as HTMLInputElement).value,firstName:(document.querySelector('#user-first') as HTMLInputElement).value,middleName:(document.querySelector('#user-middle') as HTMLInputElement).value,username:(document.querySelector('#user-login') as HTMLInputElement).value,password:(document.querySelector('#user-password') as HTMLInputElement).value,role:(document.querySelector('#user-role') as HTMLSelectElement).value,active:true};try{await api(u?`/api/users/${u.id}`:'/api/users',{method:u?'PUT':'POST',body:JSON.stringify(payload)});closeModal();toast('Пользователь сохранён');adminUsers=[];await usersPage()}catch(e){toast((e as Error).message,true)}},()=>{(document.querySelector('#user-role') as HTMLSelectElement).value=u?.role||'employee'})}

async function officesPage(){setHeader('РП','Отдельный справочник подразделений');const rows=await api<any[]>('/api/offices');content.innerHTML=`<div class="card admin-card"><div class="card-head"><div class="list-heading"><h2>РП</h2><span>${rows.filter(o=>o.active).length} активных · ${rows.filter(o=>!o.active).length} архивных</span></div><div class="page-actions"><select id="office-status" aria-label="Статус РП"><option value="active">Активные РП</option><option value="archived">Архивные РП</option><option value="all">Все РП</option></select><label class="table-search">${icons.search}<input id="office-search" type="search" placeholder="Найти РП" aria-label="Поиск РП"></label><button id="new-office" class="btn btn-primary">+ Добавить РП</button></div></div><div class="table-scroll"><table class="data-table office-table"><thead><tr><th class="order-col">Порядок</th><th>Название РП</th><th>Статус</th><th class="actions-col">Действия</th></tr></thead><tbody>${rows.map((o,i)=>`<tr data-id="${o.id}" data-active="${o.active?'true':'false'}" data-search="${esc(String(o.name).toLowerCase())}"><td><span class="drag-handle" draggable="true" aria-label="Перетащить РП"><i></i><span class="sort-value">${i+1}</span></span></td><td class="primary-cell">${esc(o.name)}</td><td><span class="state-badge ${o.active?'active':'inactive'}"><i></i>${o.active?'Активно':'Архив'}</span></td><td class="row-actions"><button class="btn btn-outline edit-office" data-id="${o.id}">${o.active?'Изменить':'Просмотреть / восстановить'}</button></td></tr>`).join('')}</tbody></table></div><div class="filter-empty" hidden>По выбранному фильтру ничего не найдено</div></div>`;const search=document.querySelector<HTMLInputElement>('#office-search')!,status=document.querySelector<HTMLSelectElement>('#office-status')!,apply=()=>{const query=search.value.trim().toLowerCase();let shown=0;content.querySelectorAll<HTMLTableRowElement>('.office-table tbody tr').forEach(row=>{const matchesStatus=status.value==='all'||(status.value==='active'&&row.dataset.active==='true')||(status.value==='archived'&&row.dataset.active==='false'),visible=matchesStatus&&(!query||(row.dataset.search||'').includes(query));row.hidden=!visible;if(visible)shown++});content.querySelector<HTMLElement>('.filter-empty')!.hidden=shown>0};search.oninput=apply;status.onchange=apply;apply();document.querySelector<HTMLButtonElement>('#new-office')!.onclick=()=>officeModal();document.querySelectorAll<HTMLButtonElement>('.edit-office').forEach(b=>b.onclick=()=>officeModal(rows.find(x=>x.id===b.dataset.id)));wireOfficeSorting()}
function wireOfficeSorting(){const tbody=content.querySelector<HTMLTableSectionElement>('.office-table tbody');if(!tbody)return;let dragged:HTMLTableRowElement|null=null;tbody.querySelectorAll<HTMLElement>('.drag-handle').forEach(handle=>{handle.ondragstart=e=>{dragged=handle.closest('tr');dragged?.classList.add('dragging');if(e.dataTransfer){e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragged?.dataset.id||'')}};handle.ondragend=()=>{dragged?.classList.remove('dragging');dragged=null;tbody.querySelectorAll('tr').forEach(row=>row.classList.remove('drag-over'))}});tbody.ondragover=e=>{if(!dragged)return;e.preventDefault();const target=(e.target as HTMLElement).closest<HTMLTableRowElement>('tr');if(!target||target===dragged)return;tbody.querySelectorAll('tr').forEach(row=>row.classList.remove('drag-over'));target.classList.add('drag-over');const after=e.clientY>target.getBoundingClientRect().top+target.offsetHeight/2;tbody.insertBefore(dragged,after?target.nextSibling:target)};tbody.ondrop=async e=>{if(!dragged)return;e.preventDefault();tbody.querySelectorAll('tr').forEach(row=>row.classList.remove('drag-over'));const ordered=[...tbody.querySelectorAll<HTMLTableRowElement>('tr')];ordered.forEach((row,i)=>{const number=row.querySelector<HTMLElement>('.sort-value');if(number)number.textContent=String(i+1)});try{await api('/api/offices/order',{method:'PUT',body:JSON.stringify({ids:ordered.map(row=>row.dataset.id)})});toast('Порядок РП сохранён')}catch(error){toast((error as Error).message,true);officesPage()}}}
function officeModal(o?:any){showModal(o?'Изменить РП':'Новое РП',`<div class="office-form"><div class="form-section-head"><b>Параметры РП</b><span>Архивное РП не добавляется в новые отчёты, но сохраняется в старых.</span></div><div class="field"><label>Название РП</label><input id="office-name" class="input" placeholder="Введите полное название" value="${esc(o?.name||'')}"></div>${o?`<label class="active-switch"><input id="office-active" type="checkbox" ${o.active?'checked':''}><span><b>РП активно</b><small>Отключите, чтобы перенести РП в архив</small></span></label>`:''}</div>`,async()=>{const x={name:(document.querySelector('#office-name') as HTMLInputElement).value,active:o?(document.querySelector('#office-active') as HTMLInputElement).checked:true};await api(o?`/api/offices/${o.id}`:'/api/offices',{method:o?'PUT':'POST',body:JSON.stringify(x)});closeModal();toast(x.active?'РП сохранено':'РП перенесено в архив');officesPage()})}
async function importsPage(){setHeader('Импорты','История фоновых операций');const rows=await api<any[]>('/api/imports');content.innerHTML=`<div class="card"><table class="data-table"><thead><tr><th>Дата</th><th>Файл</th><th>Статус</th><th>Прогресс</th><th>Импортировано</th><th>Ошибки</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString('ru')}</td><td>${esc(x.fileName)}</td><td>${statusRu(x.status)}</td><td>${x.processedRows} / ${x.totalRows}</td><td>${x.importedRows}</td><td>${(x.errors||[]).length}</td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">Импортов пока нет</div>'}</div>`}
function statusRu(s:string){return({queued:'В очереди',processing:'Обработка',completed:'Завершён',failed:'Ошибка'} as any)[s]||s}
async function settingsPage(){setHeader('Настройки','Персональный план для ежедневных отчётов');const x=await api<any>('/api/settings');content.innerHTML=`<div class="card settings-panel"><div class="card-head"><div class="list-heading"><h2>План приглашённых кандидатов</h2><span>План устанавливается на одного сотрудника</span></div></div><div class="panel-body settings-layout"><div class="setting-copy"><b>Дневной план одного сотрудника</b><p>В сводном отчёте администратора общий план рассчитывается как персональный план × количество активных сотрудников. Для старых отчётов сохраняется план, действовавший в день создания.</p></div><div class="field setting-field"><label>Количество приглашённых на сотрудника</label><div class="setting-input"><input id="setting-norm" class="input" type="text" inputmode="numeric" value="${x.invitationThreshold}"><span>человек</span></div></div></div><div class="panel-actions"><button id="save-settings" class="btn btn-primary">Сохранить настройки</button></div></div>`;document.querySelector<HTMLButtonElement>('#save-settings')!.onclick=async()=>{await api('/api/settings',{method:'PUT',body:JSON.stringify({invitationThreshold:Number((document.querySelector('#setting-norm') as HTMLInputElement).value)})});toast('Настройки сохранены')}}

function filterRows(query:string){const value=query.trim().toLowerCase();let shown=0;content.querySelectorAll<HTMLTableRowElement>('.data-table tbody tr').forEach(row=>{const visible=!value||(row.dataset.search||'').includes(value);row.hidden=!visible;if(visible)shown++});const empty=content.querySelector<HTMLElement>('.filter-empty');if(empty)empty.hidden=shown>0}
async function auditPage(){setHeader('Журнал действий','Последние изменения в системе');const rows=await api<any[]>('/api/audit');content.innerHTML=`<div class="card"><table class="data-table"><thead><tr><th>Дата и время</th><th>Пользователь</th><th>Действие</th><th>Объект</th><th>Идентификатор</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString('ru')}</td><td>${esc(x.actor)}</td><td>${esc(x.action)}</td><td>${esc(x.entityType)}</td><td class="muted">${esc(x.entityId)}</td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">Событий пока нет</div>'}</div>`}

document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.body.classList.remove('table-fullscreen')});
window.addEventListener('resize',()=>{closeDatePicker();if(currentPage==='report'&&!hasCustomColumnWidths())applyColumnWidths()});
window.addEventListener('beforeunload',e=>{if(dirtyRows.size){e.preventDefault();e.returnValue='Есть несохранённые изменения'}});
document.querySelector<HTMLButtonElement>('#logout')!.onclick=async()=>{await api('/api/auth/logout',{method:'POST',body:'{}'});currentUser=null;showLogin()};
function configureUser(){if(!currentUser)return;pages=manager()?[...reportPage,['exports',icons.download,'Выгрузка'],['users',icons.employees,'Пользователи'],['offices',icons.offices,'РП'],['settings',icons.settings,'Настройки']]:[...reportPage];const display=[currentUser.lastName,currentUser.firstName].filter(Boolean).join(' ')||currentUser.username;document.querySelector('#profile-name')!.textContent=display;document.querySelector('#profile-role')!.textContent=currentUser.role==='superadmin'?'Суперадминистратор':currentUser.role==='admin'?'Администратор':'Сотрудник';document.querySelector('#profile-avatar')!.textContent=((currentUser.firstName?.[0]||'')+(currentUser.lastName?.[0]||currentUser.username[0]||'')).toUpperCase();reportDate=businessToday();currentPage='report';selectedEmployee='';adminUsers=[];drawNav();route()}
function showLogin(message=''){document.body.classList.add('logged-out');modalRoot.innerHTML=`<div class="login-screen"><form class="login-card" id="login-form"><div class="login-brand"><span class="brand-mark">HR</span><div><strong>HR Daily</strong></div></div><div class="login-copy"><h1>Вход в систему</h1><p>Введите логин и пароль учётной записи</p></div><div class="field"><label>Логин</label><input id="login-name" class="input" autocomplete="username" autofocus></div><div class="field"><label>Пароль</label><input id="login-password" class="input" type="password" autocomplete="current-password"></div><div id="login-error" class="login-error">${esc(message)}</div><button class="btn btn-primary login-submit" type="submit">Войти</button></form></div>`;document.querySelector<HTMLFormElement>('#login-form')!.onsubmit=async e=>{e.preventDefault();const button=document.querySelector<HTMLButtonElement>('.login-submit')!;button.disabled=true;button.textContent='Вход...';try{currentUser=await api<User>('/api/auth/login',{method:'POST',body:JSON.stringify({username:(document.querySelector('#login-name') as HTMLInputElement).value,password:(document.querySelector('#login-password') as HTMLInputElement).value})});modalRoot.innerHTML='';document.body.classList.remove('logged-out');configureUser()}catch(err){document.querySelector('#login-error')!.textContent=(err as Error).message;button.disabled=false;button.textContent='Войти'}};requestAnimationFrame(()=>document.querySelector<HTMLInputElement>('#login-name')?.focus())}
async function init(){try{currentUser=await api<User>('/api/auth/me');document.body.classList.remove('logged-out');configureUser()}catch{showLogin()}}
init();
